apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kafkaconnectors.kafka.strimzi.io
spec:
  group: kafka.strimzi.io
  names:
    kind: KafkaConnector
    listKind: KafkaConnectorList
    plural: kafkaconnectors
    singular: kafkaconnector
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: KafkaConnector is the Schema for the KafkaConnector API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: KafkaConnectorSpec defines the desired state of KafkaConnectorSpec
          properties:
            class:
              type: string
            config:
              additionalProperties:
                type: string
              type: object
            pause:
              type: boolean
            tasksMax:
              type: integer
          type: object
        status:
          description: KafkaConnectorStatus defines the observed state of KafkaConnector
          properties:
            conditions:
              items:
                description: Condition defines the desired state of Condition
                properties:
                  lastTransitionTime:
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                type: object
              type: array
            connectorStatus:
              additionalProperties:
                type: string
              type: object
            observedGeneration:
              type: integer
          type: object
      type: object
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
