/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1beta1

type AlgoConfig struct {

	Applied bool `json:"applied,omitempty"`

	DeploymentName string `json:"deploymentName,omitempty"`

	AlgoOwnerUserName string `json:"algoOwnerUserName,omitempty"`

	AlgoName string `json:"algoName,omitempty"`

	AlgoVersionTag string `json:"algoVersionTag,omitempty"`

	AlgoIndex int32 `json:"algoIndex,omitempty"`

	ImageRepository string `json:"imageRepository,omitempty"`

	ImageTag string `json:"imageTag,omitempty"`

	Entrypoint string `json:"entrypoint,omitempty"`

	Executor string `json:"executor,omitempty"`

	AlgoParams []AlgoParamModel `json:"algoParams,omitempty"`

	Inputs []AlgoInputModel `json:"inputs,omitempty"`

	Outputs []AlgoOutputModel `json:"outputs,omitempty"`

	WriteAllOutputs bool `json:"writeAllOutputs,omitempty"`

	GpuEnabled bool `json:"gpuEnabled,omitempty"`

	TimeoutSeconds int32 `json:"timeoutSeconds,omitempty"`

	Resource *ResourceModel `json:"resource,omitempty"`

	AlgoRunnerImage string `json:"algoRunnerImage,omitempty"`

	AlgoRunnerImageTag string `json:"algoRunnerImageTag,omitempty"`

	LivenessInitialDelaySeconds int32 `json:"livenessInitialDelaySeconds,omitempty"`

	LivenessTimeoutSeconds int32 `json:"livenessTimeoutSeconds,omitempty"`

	LivenessPeriodSeconds int32 `json:"livenessPeriodSeconds,omitempty"`

	ReadinessInitialDelaySeconds int32 `json:"readinessInitialDelaySeconds,omitempty"`

	ReadinessTimeoutSeconds int32 `json:"readinessTimeoutSeconds,omitempty"`

	ReadinessPeriodSeconds int32 `json:"readinessPeriodSeconds,omitempty"`
}
