/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1beta1

import (
	corev1 "k8s.io/api/core/v1"
)

type ComponentPodStatus struct {
	ComponentType string `json:"componentType,omitempty"`

	Name string `json:"name,omitempty"`

	VersionTag string `json:"versionTag,omitempty"`

	Index int32 `json:"index,omitempty"`

	PodName string `json:"podName,omitempty"`

	Status string `json:"status,omitempty"`

	Restarts int32 `json:"restarts,omitempty"`

	Ip string `json:"ip,omitempty"`

	Node string `json:"node,omitempty"`

	ContainerStatuses []corev1.ContainerStatus `json:"containerStatuses,omitempty"`

	CreatedTimestamp string `json:"createdTimestamp,omitempty"`
}
