/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1beta1

type DeploymentStatusMessage struct {

	DeploymentOwnerUserName string `json:"deploymentOwnerUserName,omitempty"`

	DeploymentName string `json:"deploymentName,omitempty"`

	Status string `json:"status,omitempty"`

	ComponentStatus []ComponentStatus `json:"componentStatus,omitempty"`

	PodStatus []ComponentPodStatus `json:"podStatus,omitempty"`
}
