/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1beta1

type EndpointKafkaConfig struct {

	Brokers []string `json:"brokers,omitempty"`

	Params map[string]string `json:"params,omitempty"`
}
