/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1beta1

type EndpointServerConfig struct {

	Http *EndpointServerListen `json:"http,omitempty"`

	Grpc *EndpointServerListen `json:"grpc,omitempty"`

	Monitoring *EndpointServerListen `json:"monitoring,omitempty"`
}
