/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1beta1
// ImagePullPolicies the model 'ImagePullPolicies'
type ImagePullPolicies string

// List of ImagePullPolicies
const (
	IMAGEPULLPOLICIES_IF_NOT_PRESENT ImagePullPolicies = "IfNotPresent"
	IMAGEPULLPOLICIES_ALWAYS ImagePullPolicies = "Always"
	IMAGEPULLPOLICIES_NEVER ImagePullPolicies = "Never"
)
