/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1beta1
// AlgoConfig struct for AlgoConfig
type AlgoConfig struct {
	Applied bool `json:"applied,omitempty"`
	DeploymentOwner string `json:"deploymentOwner,omitempty"`
	DeploymentName string `json:"deploymentName,omitempty"`
	AlgoOwner string `json:"algoOwner"`
	AlgoName string `json:"algoName"`
	AlgoVersionTag string `json:"algoVersionTag"`
	AlgoIndex int32 `json:"algoIndex"`
	Image *ContainerImageModel `json:"image"`
	Entrypoint string `json:"entrypoint,omitempty"`
	Executor *Executors `json:"executor,omitempty"`
	Topics []TopicConfigModel `json:"topics,omitempty"`
	ConfigMounts []ConfigMountModel `json:"configMounts,omitempty"`
	Parameters []AlgoParamModel `json:"parameters,omitempty"`
	Inputs []AlgoInputModel `json:"inputs,omitempty"`
	Outputs []AlgoOutputModel `json:"outputs,omitempty"`
	RetryEnabled bool `json:"retryEnabled,omitempty"`
	RetryStrategy *TopicRetryStrategyModel `json:"retryStrategy,omitempty"`
	WriteAllOutputs bool `json:"writeAllOutputs,omitempty"`
	GpuEnabled bool `json:"gpuEnabled,omitempty"`
	TimeoutSeconds int32 `json:"timeoutSeconds,omitempty"`
	Resource *ResourceModel `json:"resource,omitempty"`
	AlgoRunnerImage *ContainerImageModel `json:"algoRunnerImage,omitempty"`
	LivenessProbe *ProbeModel `json:"livenessProbe,omitempty"`
	ReadinessProbe *ProbeModel `json:"readinessProbe,omitempty"`
}
