/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1beta1
// AlgoRunnerConfig struct for AlgoRunnerConfig
type AlgoRunnerConfig struct {
	DeploymentOwnerUserName string `json:"deploymentOwnerUserName"`
	DeploymentName string `json:"deploymentName"`
	PipelineOwnerUserName string `json:"pipelineOwnerUserName"`
	PipelineName string `json:"pipelineName"`
	AlgoOwnerUserName string `json:"algoOwnerUserName"`
	AlgoName string `json:"algoName"`
	AlgoVersionTag string `json:"algoVersionTag"`
	AlgoIndex int32 `json:"algoIndex"`
	Entrypoint string `json:"entrypoint,omitempty"`
	Executor *Executors `json:"executor,omitempty"`
	AlgoParams []AlgoParamModel `json:"algoParams,omitempty"`
	Inputs []AlgoInputModel `json:"inputs,omitempty"`
	Outputs []AlgoOutputModel `json:"outputs,omitempty"`
	WriteAllOutputs bool `json:"writeAllOutputs,omitempty"`
	Pipes []PipeModel `json:"pipes,omitempty"`
	TopicConfigs []TopicConfigModel `json:"topicConfigs,omitempty"`
	TopicRetryEnabled bool `json:"topicRetryEnabled,omitempty"`
	RetryStrategy *TopicRetryStrategyModel `json:"retryStrategy,omitempty"`
	GpuEnabled bool `json:"gpuEnabled,omitempty"`
	TimeoutSeconds int32 `json:"timeoutSeconds,omitempty"`
}
