/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1beta1
// LogLevels the model 'LogLevels'
type LogLevels string

// List of LogLevels
const (
	LOGLEVELS_ERROR LogLevels = "Error"
	LOGLEVELS_WARNING LogLevels = "Warning"
	LOGLEVELS_INFO LogLevels = "Info"
)
