/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1beta1
// ProducerWal struct for ProducerWal
type ProducerWal struct {
	Mode string `json:"mode,omitempty"`
	InMemory bool `json:"in_memory,omitempty"`
	Path string `json:"path,omitempty"`
	Size string `json:"size,omitempty"`
	AlwaysTopics []string `json:"always_topics,omitempty"`
	DisableTopics []string `json:"disable_topics,omitempty"`
}
