/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1beta1
// ContainerImageModel struct for ContainerImageModel
type ContainerImageModel struct {
	Repository string `json:"repository,omitempty"`
	Tag string `json:"tag,omitempty"`
	ImagePullPolicy *ImagePullPolicies `json:"imagePullPolicy,omitempty"`
}
