/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1beta1
// AlgoOutputModel struct for AlgoOutputModel
type AlgoOutputModel struct {
	Name string `json:"name"`
	Description string `json:"description,omitempty"`
	OutputDeliveryType *OutputDeliveryTypes `json:"outputDeliveryType"`
	Parameter string `json:"parameter,omitempty"`
	ContentType *ContentTypeModel `json:"contentType"`
}
