/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1beta1
// EndpointConfig struct for EndpointConfig
type EndpointConfig struct {
	DeploymentOwner string `json:"deploymentOwner,omitempty"`
	DeploymentName string `json:"deploymentName,omitempty"`
	PipelineOwner string `json:"pipelineOwner,omitempty"`
	PipelineName string `json:"pipelineName,omitempty"`
	Image *ContainerImageModel `json:"image,omitempty"`
	Resource *ResourceModel `json:"resource,omitempty"`
	Topics []TopicConfigModel `json:"topics,omitempty"`
	Paths []EndpointPathModel `json:"paths,omitempty"`
	Server *EndpointServerConfig `json:"server,omitempty"`
	Producer *EndpointProducerConfig `json:"producer,omitempty"`
	Kafka *EndpointKafkaConfig `json:"kafka,omitempty"`
	LivenessProbe *ProbeModel `json:"livenessProbe,omitempty"`
	ReadinessProbe *ProbeModel `json:"readinessProbe,omitempty"`
}
