/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1beta1
// ConfigMountModel struct for ConfigMountModel
type ConfigMountModel struct {
	Name string `json:"name"`
	MountPath string `json:"mountPath"`
	Data string `json:"data"`
}
