/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1beta1
// ProbeModel struct for ProbeModel
type ProbeModel struct {
	InitialDelaySeconds int32 `json:"initialDelaySeconds,omitempty"`
	PeriodSeconds int32 `json:"periodSeconds,omitempty"`
	FailureThreshold int32 `json:"failureThreshold,omitempty"`
}
