/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1beta1
// AlgoInputModel struct for AlgoInputModel
type AlgoInputModel struct {
	Name string `json:"name"`
	Description string `json:"description,omitempty"`
	IsRequired bool `json:"isRequired,omitempty"`
	InputDeliveryType *InputDeliveryTypes `json:"inputDeliveryType"`
	Http *AlgoInputHttpModel `json:"http,omitempty"`
	Grpc *AlgoInputGrpcModel `json:"grpc,omitempty"`
	FileParameter *AlgoInputFileModel `json:"fileParameter,omitempty"`
	ContentTypes []ContentTypeModel `json:"contentTypes"`
}
