/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1beta1
// OutputDeliveryTypes the model 'OutputDeliveryTypes'
type OutputDeliveryTypes string

// List of OutputDeliveryTypes
const (
	OUTPUTDELIVERYTYPES_STD_OUT OutputDeliveryTypes = "StdOut"
	OUTPUTDELIVERYTYPES_FILE_PARAMETER OutputDeliveryTypes = "FileParameter"
	OUTPUTDELIVERYTYPES_FOLDER_PARAMETER OutputDeliveryTypes = "FolderParameter"
	OUTPUTDELIVERYTYPES_HTTP_RESPONSE OutputDeliveryTypes = "HttpResponse"
	OUTPUTDELIVERYTYPES_KAFKA_TOPIC OutputDeliveryTypes = "KafkaTopic"
)
