/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1beta1
// PipelineDeploymentSpecV1beta1 struct for PipelineDeploymentSpecV1beta1
type PipelineDeploymentSpecV1beta1 struct {
	DeploymentNamespace string `json:"deploymentNamespace,omitempty"`
	DeploymentOwner string `json:"deploymentOwner"`
	DeploymentName string `json:"deploymentName"`
	PipelineOwner string `json:"pipelineOwner"`
	PipelineName string `json:"pipelineName"`
	PipelineVersionTag string `json:"pipelineVersionTag"`
	KafkaBrokers string `json:"kafkaBrokers"`
	StorageBucket string `json:"storageBucket,omitempty"`
	Endpoint *EndpointSpec `json:"endpoint,omitempty"`
	Algos []AlgoDeploymentV1beta1 `json:"algos,omitempty"`
	DataConnectors []DataConnectorDeploymentV1beta1 `json:"dataConnectors,omitempty"`
	EventHook *EventHookSpec `json:"eventHook,omitempty"`
	Pipes []PipeModel `json:"pipes,omitempty"`
}
