/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1beta1
// EndpointProducerConfig struct for EndpointProducerConfig
type EndpointProducerConfig struct {
	Cb ProducerCircuitBreaker `json:"cb,omitempty"`
	Resend ProducerResend `json:"resend,omitempty"`
	Wal ProducerWal `json:"wal,omitempty"`
}
