/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1beta1
// AutoScalingSpec struct for AutoScalingSpec
type AutoScalingSpec struct {
	Enabled bool `json:"enabled,omitempty"`
	MaxReplicas int32 `json:"maxReplicas,omitempty"`
	Metrics []ScaleMetricModel `json:"metrics,omitempty"`
	MinReplicas int32 `json:"minReplicas,omitempty"`
}
