/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1beta1
// DeploymentStatusMessage struct for DeploymentStatusMessage
type DeploymentStatusMessage struct {
	DeploymentOwner string `json:"deploymentOwner,omitempty"`
	DeploymentName string `json:"deploymentName,omitempty"`
	Status string `json:"status,omitempty"`
	ComponentStatus []ComponentStatus `json:"componentStatus,omitempty"`
	PodStatus []ComponentPodStatus `json:"podStatus,omitempty"`
}
