/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1beta1
// HookConfig struct for HookConfig
type HookConfig struct {
	DeploymentOwnerUserName string `json:"deploymentOwnerUserName,omitempty"`
	DeploymentName string `json:"deploymentName,omitempty"`
	PipelineOwnerUserName string `json:"pipelineOwnerUserName,omitempty"`
	PipelineName string `json:"pipelineName,omitempty"`
	ImageRepository string `json:"imageRepository,omitempty"`
	ImageTag string `json:"imageTag,omitempty"`
	Resource ResourceModel `json:"resource,omitempty"`
	WebHooks []WebHookModel `json:"webHooks,omitempty"`
	Pipes []PipeModel `json:"pipes,omitempty"`
	TopicConfigs []TopicConfigModel `json:"topicConfigs,omitempty"`
}
