/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1beta1
// ProbeV1 struct for ProbeV1
type ProbeV1 struct {
	Exec *ExecActionV1 `json:"exec,omitempty"`
	FailureThreshold int32 `json:"failureThreshold,omitempty"`
	SuccessThreshold int32 `json:"successThreshold,omitempty"`
	InitialDelaySeconds int32 `json:"initialDelaySeconds,omitempty"`
	PeriodSeconds int32 `json:"periodSeconds,omitempty"`
	TimeoutSeconds int32 `json:"timeoutSeconds,omitempty"`
	HttpGet *HttpGetActionV1 `json:"httpGet,omitempty"`
	TcpSocket *TcpSocketActionV1 `json:"tcpSocket,omitempty"`
}
