/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1beta1
// EndpointPathModel struct for EndpointPathModel
type EndpointPathModel struct {
	Name string `json:"name,omitempty"`
	IsDefault bool `json:"isDefault,omitempty"`
	Description *string `json:"description,omitempty"`
	ConnectionString *string `json:"connectionString,omitempty"`
	EndpointType EndpointTypes `json:"endpointType,omitempty"`
	MessageDataType MessageDataTypes `json:"messageDataType,omitempty"`
	ContentType ContentTypeModel `json:"contentType,omitempty"`
}
