/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1beta1
// ScaleMetricModel struct for ScaleMetricModel
type ScaleMetricModel struct {
	SourceType *MetricSourceTypes `json:"sourceType,omitempty"`
	ObjectApiVersion string `json:"objectApiVersion,omitempty"`
	ObjectKind string `json:"objectKind,omitempty"`
	ObjectName string `json:"objectName,omitempty"`
	MetricName string `json:"metricName,omitempty"`
	ResourceName string `json:"resourceName,omitempty"`
	MetricSelector string `json:"metricSelector,omitempty"`
	TargetType *MetricTargetTypes `json:"targetType,omitempty"`
	AverageUtilization int32 `json:"averageUtilization,omitempty"`
	AverageValue string `json:"averageValue,omitempty"`
	Value string `json:"value,omitempty"`
}
