/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1beta1
// ComponentTypes the model 'ComponentTypes'
type ComponentTypes string

// List of ComponentTypes
const (
	COMPONENTTYPES_ALGO ComponentTypes = "Algo"
	COMPONENTTYPES_ENDPOINT ComponentTypes = "Endpoint"
	COMPONENTTYPES_DATA_CONNECTOR ComponentTypes = "DataConnector"
	COMPONENTTYPES_HOOK ComponentTypes = "Hook"
)
