/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1beta1
// EndpointSpec struct for EndpointSpec
type EndpointSpec struct {
	Image *ContainerImageModel `json:"image,omitempty"`
	Replicas int32 `json:"replicas,omitempty"`
	Resources *ResourceRequirementsV1 `json:"resources,omitempty"`
	Autoscaling *AutoScalingSpec `json:"autoscaling,omitempty"`
	Paths []EndpointPathSpec `json:"paths,omitempty"`
	Server *EndpointServerConfig `json:"server,omitempty"`
	Producer *EndpointProducerConfig `json:"producer,omitempty"`
	Kafka *EndpointKafkaConfig `json:"kafka,omitempty"`
	LivenessProbe *ProbeV1 `json:"livenessProbe,omitempty"`
	ReadinessProbe *ProbeV1 `json:"readinessProbe,omitempty"`
}
