/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1beta1
// AlgoRunnerConfig struct for AlgoRunnerConfig
type AlgoRunnerConfig struct {
	DeploymentOwner string `json:"deploymentOwner"`
	DeploymentName string `json:"deploymentName"`
	PipelineOwner string `json:"pipelineOwner"`
	PipelineName string `json:"pipelineName"`
	AlgoOwner string `json:"algoOwner"`
	AlgoName string `json:"algoName"`
	AlgoVersionTag string `json:"algoVersionTag"`
	AlgoIndex int32 `json:"algoIndex"`
	Entrypoint string `json:"entrypoint,omitempty"`
	Executor *Executors `json:"executor,omitempty"`
	Parameters []AlgoParamModel `json:"parameters,omitempty"`
	Inputs []AlgoInputModel `json:"inputs,omitempty"`
	Outputs []AlgoOutputModel `json:"outputs,omitempty"`
	WriteAllOutputs bool `json:"writeAllOutputs,omitempty"`
	Pipes []PipeModel `json:"pipes,omitempty"`
	Topics []TopicConfigModel `json:"topics,omitempty"`
	RetryEnabled bool `json:"retryEnabled,omitempty"`
	RetryStrategy *TopicRetryStrategyModel `json:"retryStrategy,omitempty"`
	GpuEnabled bool `json:"gpuEnabled,omitempty"`
	TimeoutSeconds int32 `json:"timeoutSeconds,omitempty"`
}
