/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1beta1
// PipelineDeploymentSpecV1beta1 struct for PipelineDeploymentSpecV1beta1
type PipelineDeploymentSpecV1beta1 struct {
	DeploymentOwnerUserName string `json:"deploymentOwnerUserName"`
	DeploymentName string `json:"deploymentName"`
	PipelineOwnerUserName string `json:"pipelineOwnerUserName"`
	PipelineName string `json:"pipelineName"`
	PipelineVersionTag string `json:"pipelineVersionTag"`
	KafkaBrokers string `json:"kafkaBrokers"`
	StorageBucket string `json:"storageBucket,omitempty"`
	ImagePullPolicy string `json:"imagePullPolicy,omitempty"`
	Endpoint EndpointConfig `json:"endpoint,omitempty"`
	Algos []AlgoConfig `json:"algos,omitempty"`
	DataConnectors []DataConnectorConfig `json:"dataConnectors,omitempty"`
	Hook HookConfig `json:"hook,omitempty"`
	Pipes []PipeModel `json:"pipes,omitempty"`
}
