/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1beta1
// AlgoInputFileModel struct for AlgoInputFileModel
type AlgoInputFileModel struct {
	Parameter string `json:"parameter,omitempty"`
	Delimiter string `json:"delimiter,omitempty"`
}
