/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1beta1
// PipeModel struct for PipeModel
type PipeModel struct {
	SourceComponentType ComponentTypes `json:"sourceComponentType,omitempty"`
	SourceName string `json:"sourceName"`
	SourceOutputName string `json:"sourceOutputName"`
	SourceOutputMessageDataType MessageDataTypes `json:"sourceOutputMessageDataType,omitempty"`
	DestComponentType ComponentTypes `json:"destComponentType,omitempty"`
	DestName string `json:"destName"`
	DestInputName string `json:"destInputName"`
}
