/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1beta1
// AlgoInputHttpModel struct for AlgoInputHttpModel
type AlgoInputHttpModel struct {
	Verb string `json:"verb,omitempty"`
	Port int32 `json:"port,omitempty"`
	Path string `json:"path,omitempty"`
	Headers map[string]string `json:"headers,omitempty"`
}
