/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1beta1
// EndpointPathSpec struct for EndpointPathSpec
type EndpointPathSpec struct {
	Name string `json:"name,omitempty"`
	IsDefault bool `json:"isDefault,omitempty"`
	EndpointType *EndpointTypes `json:"endpointType,omitempty"`
	MessageDataType *MessageDataTypes `json:"messageDataType,omitempty"`
	ContentType string `json:"contentType,omitempty"`
	Topic *TopicConfigModel `json:"topic,omitempty"`
}
