/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1beta1
// AlgoParamSpec struct for AlgoParamSpec
type AlgoParamSpec struct {
	SortOrder int32 `json:"sortOrder,omitempty"`
	Required bool `json:"required,omitempty"`
	Name string `json:"name"`
	Value string `json:"value,omitempty"`
}
