/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1beta1
// AlgoVersionModel struct for AlgoVersionModel
type AlgoVersionModel struct {
	Latest bool `json:"latest,omitempty"`
	VersionTag string `json:"versionTag"`
	Image *ContainerImageModel `json:"image"`
	Entrypoint string `json:"entrypoint,omitempty"`
}
