/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1beta1
// Duration struct for Duration
type Duration struct {
	Days int32 `json:"days,omitempty"`
	NanosecondOfDay int64 `json:"nanosecondOfDay,omitempty"`
	Hours int32 `json:"hours,omitempty"`
	Minutes int32 `json:"minutes,omitempty"`
	Seconds int32 `json:"seconds,omitempty"`
	Milliseconds int32 `json:"milliseconds,omitempty"`
	SubsecondTicks int32 `json:"subsecondTicks,omitempty"`
	SubsecondNanoseconds int32 `json:"subsecondNanoseconds,omitempty"`
	BclCompatibleTicks int64 `json:"bclCompatibleTicks,omitempty"`
	TotalDays float64 `json:"totalDays,omitempty"`
	TotalHours float64 `json:"totalHours,omitempty"`
	TotalMinutes float64 `json:"totalMinutes,omitempty"`
	TotalSeconds float64 `json:"totalSeconds,omitempty"`
	TotalMilliseconds float64 `json:"totalMilliseconds,omitempty"`
	TotalTicks float64 `json:"totalTicks,omitempty"`
	TotalNanoseconds float64 `json:"totalNanoseconds,omitempty"`
}
