/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1beta1
// ProducerResend struct for ProducerResend
type ProducerResend struct {
	Period string `json:"period,omitempty"`
	RateLimit int32 `json:"rate_limit,omitempty"`
}
