/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1beta1
// TopicConfigModel struct for TopicConfigModel
type TopicConfigModel struct {
	OutputName string `json:"outputName"`
	AutoName bool `json:"autoName,omitempty"`
	TopicName string `json:"topicName,omitempty"`
	AutoPartition bool `json:"autoPartition,omitempty"`
	Partitions int32 `json:"partitions,omitempty"`
	ReplicationFactor int32 `json:"replicationFactor,omitempty"`
	TopicParams []TopicParamModel `json:"topicParams,omitempty"`
	OverrideRetryStrategy bool `json:"overrideRetryStrategy,omitempty"`
	RetryStrategy *TopicRetryStrategyModel `json:"retryStrategy,omitempty"`
}
