/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1beta1
// ContentTypeModel struct for ContentTypeModel
type ContentTypeModel struct {
	Name string `json:"name,omitempty"`
	Title string `json:"title,omitempty"`
	GroupName string `json:"groupName,omitempty"`
	SubTypeName string `json:"subTypeName,omitempty"`
	FileExtension string `json:"fileExtension,omitempty"`
	IconClass string `json:"iconClass,omitempty"`
}
