/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1beta1
// DataConnectorSpecV1beta1 struct for DataConnectorSpecV1beta1
type DataConnectorSpecV1beta1 struct {
	DataConnectorType *DataConnectorTypes `json:"dataConnectorType,omitempty"`
	Name string `json:"name,omitempty"`
	Versions []DataConnectorVersionModel `json:"versions"`
	ConnectorClass string `json:"connectorClass,omitempty"`
	Options []DataConnectorOptionModel `json:"options,omitempty"`
}
