/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1beta1
// MetricTargetTypes the model 'MetricTargetTypes'
type MetricTargetTypes string

// List of MetricTargetTypes
const (
	METRICTARGETTYPES_UTILIZATION MetricTargetTypes = "Utilization"
	METRICTARGETTYPES_VALUE MetricTargetTypes = "Value"
	METRICTARGETTYPES_AVERAGE_VALUE MetricTargetTypes = "AverageValue"
)
