/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1beta1
// AlgoDeploymentV1beta1 struct for AlgoDeploymentV1beta1
type AlgoDeploymentV1beta1 struct {
	AlgoRef *CustomResourceRefV1beta1 `json:"algoRef,omitempty"`
	Version string `json:"version"`
	Index int32 `json:"index"`
	ConfigMounts []ConfigMountModel `json:"configMounts,omitempty"`
	Parameters []AlgoParamSpec `json:"parameters,omitempty"`
	RetryEnabled bool `json:"retryEnabled,omitempty"`
	RetryStrategy *TopicRetryStrategyModel `json:"retryStrategy,omitempty"`
	WriteAllOutputs bool `json:"writeAllOutputs,omitempty"`
	TimeoutSeconds int32 `json:"timeoutSeconds,omitempty"`
	Topics []TopicConfigModel `json:"topics,omitempty"`
	AlgoRunnerImage *ContainerImageModel `json:"algoRunnerImage,omitempty"`
	Replicas int32 `json:"replicas,omitempty"`
	Resources *ResourceRequirementsV1 `json:"resources,omitempty"`
	Autoscaling *AutoScalingSpec `json:"autoscaling,omitempty"`
	LivenessProbe *ProbeV1 `json:"livenessProbe,omitempty"`
	ReadinessProbe *ProbeV1 `json:"readinessProbe,omitempty"`
	Spec *AlgoSpecV1beta1 `json:"spec,omitempty"`
}
