/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1beta1
// WebHookModel struct for WebHookModel
type WebHookModel struct {
	DeploymentOwnerUserName string `json:"deploymentOwnerUserName,omitempty"`
	DeploymentName string `json:"deploymentName,omitempty"`
	PipelineHookInputName string `json:"pipelineHookInputName,omitempty"`
	WebHookUrl string `json:"webHookUrl,omitempty"`
	HttpVerb string `json:"httpVerb,omitempty"`
	HttpHeaders string `json:"httpHeaders,omitempty"`
}
