/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1beta1
// TcpSocketActionV1 struct for TcpSocketActionV1
type TcpSocketActionV1 struct {
	Host string `json:"host,omitempty"`
	Port *Int32OrStringV1 `json:"port,omitempty"`
}
