/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1beta1
// ExecActionV1 struct for ExecActionV1
type ExecActionV1 struct {
	Command []string `json:"command,omitempty"`
}
