/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1beta1
// EndpointConfig struct for EndpointConfig
type EndpointConfig struct {
	DeploymentOwnerUserName string `json:"deploymentOwnerUserName,omitempty"`
	DeploymentName string `json:"deploymentName,omitempty"`
	PipelineOwnerUserName string `json:"pipelineOwnerUserName,omitempty"`
	PipelineName string `json:"pipelineName,omitempty"`
	ImageRepository string `json:"imageRepository,omitempty"`
	ImageTag string `json:"imageTag,omitempty"`
	Resource ResourceModel `json:"resource,omitempty"`
	TopicConfigs []TopicConfigModel `json:"topicConfigs,omitempty"`
	Paths []EndpointPathModel `json:"paths,omitempty"`
	Server *EndpointServerConfig `json:"server,omitempty"`
	Producer *EndpointProducerConfig `json:"producer,omitempty"`
	Kafka EndpointKafkaConfig `json:"kafka,omitempty"`
}
