/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1beta1
// TopicRetryStrategyModel struct for TopicRetryStrategyModel
type TopicRetryStrategyModel struct {
	Strategy RetryStrategies `json:"strategy,omitempty"`
	DeadLetterSuffix *string `json:"deadLetterSuffix,omitempty"`
	Steps []TopicRetryStepModel `json:"steps,omitempty"`
}
