/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1beta1
// EndpointTypes the model 'EndpointTypes'
type EndpointTypes string

// List of EndpointTypes
const (
	ENDPOINTTYPES_HTTP EndpointTypes = "HTTP"
	ENDPOINTTYPES_RTMP EndpointTypes = "RTMP"
	ENDPOINTTYPES_KAFKA EndpointTypes = "Kafka"
	ENDPOINTTYPES_G_RPC EndpointTypes = "gRPC"
)
