/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1beta1
// RetryStrategies the model 'RetryStrategies'
type RetryStrategies string

// List of RetryStrategies
const (
	RETRYSTRATEGIES_SIMPLE RetryStrategies = "Simple"
	RETRYSTRATEGIES_RETRY_TOPICS RetryStrategies = "RetryTopics"
	RETRYSTRATEGIES_STATEFUL_ORDERED RetryStrategies = "StatefulOrdered"
	RETRYSTRATEGIES_STATEFUL_UNORDERED RetryStrategies = "StatefulUnordered"
)
