/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1beta1
// CustomResourceRefV1beta1 struct for CustomResourceRefV1beta1
type CustomResourceRefV1beta1 struct {
	Namespace string `json:"namespace,omitempty"`
	Name string `json:"name,omitempty"`
	MatchLabels map[string]string `json:"matchLabels,omitempty"`
}
