/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1beta1
// DataConnectorVersionModel struct for DataConnectorVersionModel
type DataConnectorVersionModel struct {
	VersionTag string `json:"versionTag,omitempty"`
	Image *ContainerImageModel `json:"image"`
}
