/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1beta1
// LogTypes the model 'LogTypes'
type LogTypes string

// List of LogTypes
const (
	LOGTYPES_SERVER LogTypes = "Server"
	LOGTYPES_RUNNER LogTypes = "Runner"
	LOGTYPES_ALGO LogTypes = "Algo"
	LOGTYPES_DATA LogTypes = "Data"
	LOGTYPES_OPERATOR LogTypes = "Operator"
	LOGTYPES_EVENT_HOOK LogTypes = "EventHook"
	LOGTYPES_DATA_CONNECTOR LogTypes = "DataConnector"
	LOGTYPES_ENDPOINT LogTypes = "Endpoint"
	LOGTYPES_PIPELINE LogTypes = "Pipeline"
	LOGTYPES_API LogTypes = "API"
)
