/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1beta1
// DataConnectorTypes the model 'DataConnectorTypes'
type DataConnectorTypes string

// List of DataConnectorTypes
const (
	DATACONNECTORTYPES_SOURCE DataConnectorTypes = "Source"
	DATACONNECTORTYPES_SINK DataConnectorTypes = "Sink"
)
