/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1beta1
// AlgoInputGrpcModel struct for AlgoInputGrpcModel
type AlgoInputGrpcModel struct {
	Port int32 `json:"port,omitempty"`
	Protofile string `json:"protofile,omitempty"`
}
