/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1beta1
// EndpointServerConfig struct for EndpointServerConfig
type EndpointServerConfig struct {
	Http *EndpointServerListen `json:"http,omitempty"`
	Grpc *EndpointServerListen `json:"grpc,omitempty"`
	Monitoring *EndpointServerListen `json:"monitoring,omitempty"`
}
