/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1beta1
// ComponentContainerStatus struct for ComponentContainerStatus
type ComponentContainerStatus struct {
	Name string `json:"name,omitempty"`
	Status string `json:"status,omitempty"`
	Messages []string `json:"messages,omitempty"`
}
