/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1beta1

type PipelineDeploymentSpecV1beta1 struct {

	DeploymentOwnerUserName string `json:"deploymentOwnerUserName,omitempty"`

	DeploymentName string `json:"deploymentName,omitempty"`

	PipelineOwnerUserName string `json:"pipelineOwnerUserName,omitempty"`

	PipelineName string `json:"pipelineName,omitempty"`

	PipelineVersionTag string `json:"pipelineVersionTag,omitempty"`

	KafkaBrokers string `json:"kafkaBrokers,omitempty"`

	StorageBucket string `json:"storageBucket,omitempty"`

	ImagePullPolicy string `json:"imagePullPolicy,omitempty"`

	Endpoint *EndpointConfig `json:"endpoint,omitempty"`

	Algos []AlgoConfig `json:"algos,omitempty"`

	DataConnectors []DataConnectorConfig `json:"dataConnectors,omitempty"`

	Hook *HookConfig `json:"hook,omitempty"`

	Pipes []PipeModel `json:"pipes,omitempty"`
}
