/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1beta1

type PipelineSpec struct {

	DeploymentOwnerUserName string `json:"deploymentOwnerUserName,omitempty"`

	DeploymentName string `json:"deploymentName,omitempty"`

	PipelineOwnerUserName string `json:"pipelineOwnerUserName,omitempty"`

	PipelineName string `json:"pipelineName,omitempty"`

	PipelineVersionTag string `json:"pipelineVersionTag,omitempty"`

	StorageBucket string `json:"storageBucket,omitempty"`

	ImagePullPolicy string `json:"imagePullPolicy,omitempty"`

	EndpointConfig *EndpointConfig `json:"endpointConfig,omitempty"`

	AlgoConfigs []AlgoConfig `json:"algoConfigs,omitempty"`

	DataConnectorConfigs []DataConnectorConfig `json:"dataConnectorConfigs,omitempty"`

	HookConfig *HookConfig `json:"hookConfig,omitempty"`

	TopicConfigs []TopicConfigModel `json:"topicConfigs,omitempty"`

	Pipes []PipeModel `json:"pipes,omitempty"`
}
