/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1beta1

type ResourceModel struct {

	MemoryRequestBytes int64 `json:"memoryRequestBytes,omitempty"`

	MemoryLimitBytes int64 `json:"memoryLimitBytes,omitempty"`

	CpuRequestMillicores int64 `json:"cpuRequestMillicores,omitempty"`

	CpuLimitMillicores int64 `json:"cpuLimitMillicores,omitempty"`

	GpuLimitMillicores int64 `json:"gpuLimitMillicores,omitempty"`

	Instances int32 `json:"instances,omitempty"`

	AutoScale bool `json:"autoScale,omitempty"`

	MinInstances int32 `json:"minInstances,omitempty"`

	MaxInstances int32 `json:"maxInstances,omitempty"`

	ScaleMetrics []ScaleMetricModel `json:"scaleMetrics,omitempty"`
}
