/*
 * Algo.Run API 1.0-beta1
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0-beta1
 * Contact: support@algohub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1beta1

type TopicConfigModel struct {

	ComponentType string `json:"componentType,omitempty"`

	SourceName string `json:"sourceName,omitempty"`

	SourceOutputName string `json:"sourceOutputName,omitempty"`

	TopicAutoName bool `json:"topicAutoName,omitempty"`

	TopicName string `json:"topicName,omitempty"`

	TopicAutoPartition bool `json:"topicAutoPartition,omitempty"`

	TopicPartitions int32 `json:"topicPartitions,omitempty"`

	TopicReplicationFactor int32 `json:"topicReplicationFactor,omitempty"`

	TopicParams []TopicParamModel `json:"topicParams,omitempty"`
}
