// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlgoConfig) DeepCopyInto(out *AlgoConfig) {
	*out = *in
	if in.TopicConfigs != nil {
		in, out := &in.TopicConfigs, &out.TopicConfigs
		*out = make([]TopicConfigModel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ConfigMounts != nil {
		in, out := &in.ConfigMounts, &out.ConfigMounts
		*out = make([]ConfigMountModel, len(*in))
		copy(*out, *in)
	}
	if in.AlgoParams != nil {
		in, out := &in.AlgoParams, &out.AlgoParams
		*out = make([]AlgoParamModel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Inputs != nil {
		in, out := &in.Inputs, &out.Inputs
		*out = make([]AlgoInputModel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Outputs != nil {
		in, out := &in.Outputs, &out.Outputs
		*out = make([]AlgoOutputModel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.RetryStrategy.DeepCopyInto(&out.RetryStrategy)
	in.Resource.DeepCopyInto(&out.Resource)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlgoConfig.
func (in *AlgoConfig) DeepCopy() *AlgoConfig {
	if in == nil {
		return nil
	}
	out := new(AlgoConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlgoInputModel) DeepCopyInto(out *AlgoInputModel) {
	*out = *in
	if in.Parameter != nil {
		in, out := &in.Parameter, &out.Parameter
		*out = new(string)
		**out = **in
	}
	if in.ParameterDelimiter != nil {
		in, out := &in.ParameterDelimiter, &out.ParameterDelimiter
		*out = new(string)
		**out = **in
	}
	if in.EnvironmentVariable != nil {
		in, out := &in.EnvironmentVariable, &out.EnvironmentVariable
		*out = new(string)
		**out = **in
	}
	if in.HttpVerb != nil {
		in, out := &in.HttpVerb, &out.HttpVerb
		*out = new(string)
		**out = **in
	}
	if in.HttpPath != nil {
		in, out := &in.HttpPath, &out.HttpPath
		*out = new(string)
		**out = **in
	}
	if in.HttpHeaders != nil {
		in, out := &in.HttpHeaders, &out.HttpHeaders
		*out = new(string)
		**out = **in
	}
	if in.ContentTypes != nil {
		in, out := &in.ContentTypes, &out.ContentTypes
		*out = make([]ContentTypeModel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlgoInputModel.
func (in *AlgoInputModel) DeepCopy() *AlgoInputModel {
	if in == nil {
		return nil
	}
	out := new(AlgoInputModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlgoOutputModel) DeepCopyInto(out *AlgoOutputModel) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Parameter != nil {
		in, out := &in.Parameter, &out.Parameter
		*out = new(string)
		**out = **in
	}
	in.ContentType.DeepCopyInto(&out.ContentType)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlgoOutputModel.
func (in *AlgoOutputModel) DeepCopy() *AlgoOutputModel {
	if in == nil {
		return nil
	}
	out := new(AlgoOutputModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlgoParamModel) DeepCopyInto(out *AlgoParamModel) {
	*out = *in
	if in.SortOrder != nil {
		in, out := &in.SortOrder, &out.SortOrder
		*out = new(int32)
		**out = **in
	}
	in.DataType.DeepCopyInto(&out.DataType)
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make([]DataTypeOptionModel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlgoParamModel.
func (in *AlgoParamModel) DeepCopy() *AlgoParamModel {
	if in == nil {
		return nil
	}
	out := new(AlgoParamModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlgoRunnerConfig) DeepCopyInto(out *AlgoRunnerConfig) {
	*out = *in
	if in.AlgoParams != nil {
		in, out := &in.AlgoParams, &out.AlgoParams
		*out = make([]AlgoParamModel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Inputs != nil {
		in, out := &in.Inputs, &out.Inputs
		*out = make([]AlgoInputModel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Outputs != nil {
		in, out := &in.Outputs, &out.Outputs
		*out = make([]AlgoOutputModel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Pipes != nil {
		in, out := &in.Pipes, &out.Pipes
		*out = make([]PipeModel, len(*in))
		copy(*out, *in)
	}
	if in.TopicConfigs != nil {
		in, out := &in.TopicConfigs, &out.TopicConfigs
		*out = make([]TopicConfigModel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.RetryStrategy.DeepCopyInto(&out.RetryStrategy)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlgoRunnerConfig.
func (in *AlgoRunnerConfig) DeepCopy() *AlgoRunnerConfig {
	if in == nil {
		return nil
	}
	out := new(AlgoRunnerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentPodStatus) DeepCopyInto(out *ComponentPodStatus) {
	*out = *in
	if in.ContainerStatuses != nil {
		in, out := &in.ContainerStatuses, &out.ContainerStatuses
		*out = make([]v1.ContainerStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentPodStatus.
func (in *ComponentPodStatus) DeepCopy() *ComponentPodStatus {
	if in == nil {
		return nil
	}
	out := new(ComponentPodStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentStatus) DeepCopyInto(out *ComponentStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentStatus.
func (in *ComponentStatus) DeepCopy() *ComponentStatus {
	if in == nil {
		return nil
	}
	out := new(ComponentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMountModel) DeepCopyInto(out *ConfigMountModel) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMountModel.
func (in *ConfigMountModel) DeepCopy() *ConfigMountModel {
	if in == nil {
		return nil
	}
	out := new(ConfigMountModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContentTypeModel) DeepCopyInto(out *ContentTypeModel) {
	*out = *in
	if in.GroupName != nil {
		in, out := &in.GroupName, &out.GroupName
		*out = new(string)
		**out = **in
	}
	if in.SubTypeName != nil {
		in, out := &in.SubTypeName, &out.SubTypeName
		*out = new(string)
		**out = **in
	}
	if in.FileExtension != nil {
		in, out := &in.FileExtension, &out.FileExtension
		*out = new(string)
		**out = **in
	}
	if in.IconClass != nil {
		in, out := &in.IconClass, &out.IconClass
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContentTypeModel.
func (in *ContentTypeModel) DeepCopy() *ContentTypeModel {
	if in == nil {
		return nil
	}
	out := new(ContentTypeModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataConnectorConfig) DeepCopyInto(out *DataConnectorConfig) {
	*out = *in
	if in.TopicConfigs != nil {
		in, out := &in.TopicConfigs, &out.TopicConfigs
		*out = make([]TopicConfigModel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make([]DataConnectorOptionModel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataConnectorConfig.
func (in *DataConnectorConfig) DeepCopy() *DataConnectorConfig {
	if in == nil {
		return nil
	}
	out := new(DataConnectorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataConnectorOptionModel) DeepCopyInto(out *DataConnectorOptionModel) {
	*out = *in
	if in.SortOrder != nil {
		in, out := &in.SortOrder, &out.SortOrder
		*out = new(int32)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	in.DataType.DeepCopyInto(&out.DataType)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataConnectorOptionModel.
func (in *DataConnectorOptionModel) DeepCopy() *DataConnectorOptionModel {
	if in == nil {
		return nil
	}
	out := new(DataConnectorOptionModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataTypeModel) DeepCopyInto(out *DataTypeModel) {
	*out = *in
	if in.Regex != nil {
		in, out := &in.Regex, &out.Regex
		*out = new(string)
		**out = **in
	}
	if in.Precision != nil {
		in, out := &in.Precision, &out.Precision
		*out = new(int32)
		**out = **in
	}
	if in.Scale != nil {
		in, out := &in.Scale, &out.Scale
		*out = new(int32)
		**out = **in
	}
	if in.Mask != nil {
		in, out := &in.Mask, &out.Mask
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataTypeModel.
func (in *DataTypeModel) DeepCopy() *DataTypeModel {
	if in == nil {
		return nil
	}
	out := new(DataTypeModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataTypeOptionModel) DeepCopyInto(out *DataTypeOptionModel) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataTypeOptionModel.
func (in *DataTypeOptionModel) DeepCopy() *DataTypeOptionModel {
	if in == nil {
		return nil
	}
	out := new(DataTypeOptionModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeepCopyTime.
func (in *DeepCopyTime) DeepCopy() *DeepCopyTime {
	if in == nil {
		return nil
	}
	out := new(DeepCopyTime)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentStatusMessage) DeepCopyInto(out *DeploymentStatusMessage) {
	*out = *in
	if in.ComponentStatus != nil {
		in, out := &in.ComponentStatus, &out.ComponentStatus
		*out = make([]ComponentStatus, len(*in))
		copy(*out, *in)
	}
	if in.PodStatus != nil {
		in, out := &in.PodStatus, &out.PodStatus
		*out = make([]ComponentPodStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentStatusMessage.
func (in *DeploymentStatusMessage) DeepCopy() *DeploymentStatusMessage {
	if in == nil {
		return nil
	}
	out := new(DeploymentStatusMessage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Duration) DeepCopyInto(out *Duration) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Duration.
func (in *Duration) DeepCopy() *Duration {
	if in == nil {
		return nil
	}
	out := new(Duration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointConfig) DeepCopyInto(out *EndpointConfig) {
	*out = *in
	in.Resource.DeepCopyInto(&out.Resource)
	if in.TopicConfigs != nil {
		in, out := &in.TopicConfigs, &out.TopicConfigs
		*out = make([]TopicConfigModel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Paths != nil {
		in, out := &in.Paths, &out.Paths
		*out = make([]EndpointPathModel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Server = in.Server
	in.Producer.DeepCopyInto(&out.Producer)
	in.Kafka.DeepCopyInto(&out.Kafka)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointConfig.
func (in *EndpointConfig) DeepCopy() *EndpointConfig {
	if in == nil {
		return nil
	}
	out := new(EndpointConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointKafkaConfig) DeepCopyInto(out *EndpointKafkaConfig) {
	*out = *in
	if in.Brokers != nil {
		in, out := &in.Brokers, &out.Brokers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointKafkaConfig.
func (in *EndpointKafkaConfig) DeepCopy() *EndpointKafkaConfig {
	if in == nil {
		return nil
	}
	out := new(EndpointKafkaConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointPathModel) DeepCopyInto(out *EndpointPathModel) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.ConnectionString != nil {
		in, out := &in.ConnectionString, &out.ConnectionString
		*out = new(string)
		**out = **in
	}
	in.ContentType.DeepCopyInto(&out.ContentType)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointPathModel.
func (in *EndpointPathModel) DeepCopy() *EndpointPathModel {
	if in == nil {
		return nil
	}
	out := new(EndpointPathModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointProducerConfig) DeepCopyInto(out *EndpointProducerConfig) {
	*out = *in
	out.Cb = in.Cb
	out.Resend = in.Resend
	in.Wal.DeepCopyInto(&out.Wal)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointProducerConfig.
func (in *EndpointProducerConfig) DeepCopy() *EndpointProducerConfig {
	if in == nil {
		return nil
	}
	out := new(EndpointProducerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointServerConfig) DeepCopyInto(out *EndpointServerConfig) {
	*out = *in
	out.Http = in.Http
	out.Grpc = in.Grpc
	out.Monitoring = in.Monitoring
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointServerConfig.
func (in *EndpointServerConfig) DeepCopy() *EndpointServerConfig {
	if in == nil {
		return nil
	}
	out := new(EndpointServerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointServerListen) DeepCopyInto(out *EndpointServerListen) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointServerListen.
func (in *EndpointServerListen) DeepCopy() *EndpointServerListen {
	if in == nil {
		return nil
	}
	out := new(EndpointServerListen)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HookConfig) DeepCopyInto(out *HookConfig) {
	*out = *in
	in.Resource.DeepCopyInto(&out.Resource)
	if in.WebHooks != nil {
		in, out := &in.WebHooks, &out.WebHooks
		*out = make([]WebHookModel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Pipes != nil {
		in, out := &in.Pipes, &out.Pipes
		*out = make([]PipeModel, len(*in))
		copy(*out, *in)
	}
	if in.TopicConfigs != nil {
		in, out := &in.TopicConfigs, &out.TopicConfigs
		*out = make([]TopicConfigModel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HookConfig.
func (in *HookConfig) DeepCopy() *HookConfig {
	if in == nil {
		return nil
	}
	out := new(HookConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotifMessage) DeepCopyInto(out *NotifMessage) {
	*out = *in
	in.MessageTimestamp = out.MessageTimestamp
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
	if in.Summary != nil {
		in, out := &in.Summary, &out.Summary
		*out = new(string)
		**out = **in
	}
	if in.Url != nil {
		in, out := &in.Url, &out.Url
		*out = new(string)
		**out = **in
	}
	in.DeploymentStatusMessage.DeepCopyInto(&out.DeploymentStatusMessage)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotifMessage.
func (in *NotifMessage) DeepCopy() *NotifMessage {
	if in == nil {
		return nil
	}
	out := new(NotifMessage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipeModel) DeepCopyInto(out *PipeModel) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipeModel.
func (in *PipeModel) DeepCopy() *PipeModel {
	if in == nil {
		return nil
	}
	out := new(PipeModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineDeployment) DeepCopyInto(out *PipelineDeployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineDeployment.
func (in *PipelineDeployment) DeepCopy() *PipelineDeployment {
	if in == nil {
		return nil
	}
	out := new(PipelineDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PipelineDeployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineDeploymentList) DeepCopyInto(out *PipelineDeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PipelineDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineDeploymentList.
func (in *PipelineDeploymentList) DeepCopy() *PipelineDeploymentList {
	if in == nil {
		return nil
	}
	out := new(PipelineDeploymentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PipelineDeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineDeploymentSpecV1beta1) DeepCopyInto(out *PipelineDeploymentSpecV1beta1) {
	*out = *in
	in.Endpoint.DeepCopyInto(&out.Endpoint)
	if in.Algos != nil {
		in, out := &in.Algos, &out.Algos
		*out = make([]AlgoConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DataConnectors != nil {
		in, out := &in.DataConnectors, &out.DataConnectors
		*out = make([]DataConnectorConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Hook.DeepCopyInto(&out.Hook)
	if in.Pipes != nil {
		in, out := &in.Pipes, &out.Pipes
		*out = make([]PipeModel, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineDeploymentSpecV1beta1.
func (in *PipelineDeploymentSpecV1beta1) DeepCopy() *PipelineDeploymentSpecV1beta1 {
	if in == nil {
		return nil
	}
	out := new(PipelineDeploymentSpecV1beta1)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineDeploymentStatus) DeepCopyInto(out *PipelineDeploymentStatus) {
	*out = *in
	if in.ComponentStatuses != nil {
		in, out := &in.ComponentStatuses, &out.ComponentStatuses
		*out = make([]ComponentStatus, len(*in))
		copy(*out, *in)
	}
	if in.PodStatuses != nil {
		in, out := &in.PodStatuses, &out.PodStatuses
		*out = make([]ComponentPodStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineDeploymentStatus.
func (in *PipelineDeploymentStatus) DeepCopy() *PipelineDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(PipelineDeploymentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProducerCircuitBreaker) DeepCopyInto(out *ProducerCircuitBreaker) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProducerCircuitBreaker.
func (in *ProducerCircuitBreaker) DeepCopy() *ProducerCircuitBreaker {
	if in == nil {
		return nil
	}
	out := new(ProducerCircuitBreaker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProducerResend) DeepCopyInto(out *ProducerResend) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProducerResend.
func (in *ProducerResend) DeepCopy() *ProducerResend {
	if in == nil {
		return nil
	}
	out := new(ProducerResend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProducerWal) DeepCopyInto(out *ProducerWal) {
	*out = *in
	if in.AlwaysTopics != nil {
		in, out := &in.AlwaysTopics, &out.AlwaysTopics
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DisableTopics != nil {
		in, out := &in.DisableTopics, &out.DisableTopics
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProducerWal.
func (in *ProducerWal) DeepCopy() *ProducerWal {
	if in == nil {
		return nil
	}
	out := new(ProducerWal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceModel) DeepCopyInto(out *ResourceModel) {
	*out = *in
	if in.ScaleMetrics != nil {
		in, out := &in.ScaleMetrics, &out.ScaleMetrics
		*out = make([]ScaleMetricModel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceModel.
func (in *ResourceModel) DeepCopy() *ResourceModel {
	if in == nil {
		return nil
	}
	out := new(ResourceModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleMetricModel) DeepCopyInto(out *ScaleMetricModel) {
	*out = *in
	if in.ObjectApiVersion != nil {
		in, out := &in.ObjectApiVersion, &out.ObjectApiVersion
		*out = new(string)
		**out = **in
	}
	if in.ObjectKind != nil {
		in, out := &in.ObjectKind, &out.ObjectKind
		*out = new(string)
		**out = **in
	}
	if in.ObjectName != nil {
		in, out := &in.ObjectName, &out.ObjectName
		*out = new(string)
		**out = **in
	}
	if in.MetricName != nil {
		in, out := &in.MetricName, &out.MetricName
		*out = new(string)
		**out = **in
	}
	if in.ResourceName != nil {
		in, out := &in.ResourceName, &out.ResourceName
		*out = new(string)
		**out = **in
	}
	if in.MetricSelector != nil {
		in, out := &in.MetricSelector, &out.MetricSelector
		*out = new(string)
		**out = **in
	}
	if in.AverageUtilization != nil {
		in, out := &in.AverageUtilization, &out.AverageUtilization
		*out = new(int32)
		**out = **in
	}
	if in.AverageValue != nil {
		in, out := &in.AverageValue, &out.AverageValue
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleMetricModel.
func (in *ScaleMetricModel) DeepCopy() *ScaleMetricModel {
	if in == nil {
		return nil
	}
	out := new(ScaleMetricModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopicConfigModel) DeepCopyInto(out *TopicConfigModel) {
	*out = *in
	if in.TopicParams != nil {
		in, out := &in.TopicParams, &out.TopicParams
		*out = make([]TopicParamModel, len(*in))
		copy(*out, *in)
	}
	in.RetryStrategy.DeepCopyInto(&out.RetryStrategy)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopicConfigModel.
func (in *TopicConfigModel) DeepCopy() *TopicConfigModel {
	if in == nil {
		return nil
	}
	out := new(TopicConfigModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopicParamModel) DeepCopyInto(out *TopicParamModel) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopicParamModel.
func (in *TopicParamModel) DeepCopy() *TopicParamModel {
	if in == nil {
		return nil
	}
	out := new(TopicParamModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopicRetryStepModel) DeepCopyInto(out *TopicRetryStepModel) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopicRetryStepModel.
func (in *TopicRetryStepModel) DeepCopy() *TopicRetryStepModel {
	if in == nil {
		return nil
	}
	out := new(TopicRetryStepModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopicRetryStrategyModel) DeepCopyInto(out *TopicRetryStrategyModel) {
	*out = *in
	if in.DeadLetterSuffix != nil {
		in, out := &in.DeadLetterSuffix, &out.DeadLetterSuffix
		*out = new(string)
		**out = **in
	}
	if in.Steps != nil {
		in, out := &in.Steps, &out.Steps
		*out = make([]TopicRetryStepModel, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopicRetryStrategyModel.
func (in *TopicRetryStrategyModel) DeepCopy() *TopicRetryStrategyModel {
	if in == nil {
		return nil
	}
	out := new(TopicRetryStrategyModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebHookModel) DeepCopyInto(out *WebHookModel) {
	*out = *in
	if in.DeploymentOwnerUserName != nil {
		in, out := &in.DeploymentOwnerUserName, &out.DeploymentOwnerUserName
		*out = new(string)
		**out = **in
	}
	if in.DeploymentName != nil {
		in, out := &in.DeploymentName, &out.DeploymentName
		*out = new(string)
		**out = **in
	}
	if in.PipelineHookInputName != nil {
		in, out := &in.PipelineHookInputName, &out.PipelineHookInputName
		*out = new(string)
		**out = **in
	}
	if in.WebHookUrl != nil {
		in, out := &in.WebHookUrl, &out.WebHookUrl
		*out = new(string)
		**out = **in
	}
	if in.HttpVerb != nil {
		in, out := &in.HttpVerb, &out.HttpVerb
		*out = new(string)
		**out = **in
	}
	if in.HttpHeaders != nil {
		in, out := &in.HttpHeaders, &out.HttpHeaders
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebHookModel.
func (in *WebHookModel) DeepCopy() *WebHookModel {
	if in == nil {
		return nil
	}
	out := new(WebHookModel)
	in.DeepCopyInto(out)
	return out
}
