// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Algo) DeepCopyInto(out *Algo) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Algo.
func (in *Algo) DeepCopy() *Algo {
	if in == nil {
		return nil
	}
	out := new(Algo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Algo) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlgoDeploymentV1beta1) DeepCopyInto(out *AlgoDeploymentV1beta1) {
	*out = *in
	if in.AlgoRef != nil {
		in, out := &in.AlgoRef, &out.AlgoRef
		*out = new(CustomResourceRefV1beta1)
		(*in).DeepCopyInto(*out)
	}
	if in.ConfigMounts != nil {
		in, out := &in.ConfigMounts, &out.ConfigMounts
		*out = make([]ConfigMountModel, len(*in))
		copy(*out, *in)
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make([]AlgoParamSpec, len(*in))
		copy(*out, *in)
	}
	if in.RetryStrategy != nil {
		in, out := &in.RetryStrategy, &out.RetryStrategy
		*out = new(TopicRetryStrategyModel)
		(*in).DeepCopyInto(*out)
	}
	if in.Topics != nil {
		in, out := &in.Topics, &out.Topics
		*out = make([]TopicConfigModel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AlgoRunnerImage != nil {
		in, out := &in.AlgoRunnerImage, &out.AlgoRunnerImage
		*out = new(ContainerImageModel)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourceRequirementsV1)
		(*in).DeepCopyInto(*out)
	}
	if in.Autoscaling != nil {
		in, out := &in.Autoscaling, &out.Autoscaling
		*out = new(AutoScalingSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.LivenessProbe != nil {
		in, out := &in.LivenessProbe, &out.LivenessProbe
		*out = new(ProbeV1)
		(*in).DeepCopyInto(*out)
	}
	if in.ReadinessProbe != nil {
		in, out := &in.ReadinessProbe, &out.ReadinessProbe
		*out = new(ProbeV1)
		(*in).DeepCopyInto(*out)
	}
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(AlgoSpecV1beta1)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlgoDeploymentV1beta1.
func (in *AlgoDeploymentV1beta1) DeepCopy() *AlgoDeploymentV1beta1 {
	if in == nil {
		return nil
	}
	out := new(AlgoDeploymentV1beta1)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlgoInputModel) DeepCopyInto(out *AlgoInputModel) {
	*out = *in
	if in.InputDeliveryType != nil {
		in, out := &in.InputDeliveryType, &out.InputDeliveryType
		*out = new(InputDeliveryTypes)
		**out = **in
	}
	if in.ContentTypes != nil {
		in, out := &in.ContentTypes, &out.ContentTypes
		*out = make([]ContentTypeModel, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlgoInputModel.
func (in *AlgoInputModel) DeepCopy() *AlgoInputModel {
	if in == nil {
		return nil
	}
	out := new(AlgoInputModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlgoInputSpec) DeepCopyInto(out *AlgoInputSpec) {
	*out = *in
	if in.InputDeliveryType != nil {
		in, out := &in.InputDeliveryType, &out.InputDeliveryType
		*out = new(InputDeliveryTypes)
		**out = **in
	}
	if in.ContentTypes != nil {
		in, out := &in.ContentTypes, &out.ContentTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlgoInputSpec.
func (in *AlgoInputSpec) DeepCopy() *AlgoInputSpec {
	if in == nil {
		return nil
	}
	out := new(AlgoInputSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlgoList) DeepCopyInto(out *AlgoList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Algo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlgoList.
func (in *AlgoList) DeepCopy() *AlgoList {
	if in == nil {
		return nil
	}
	out := new(AlgoList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AlgoList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlgoOutputModel) DeepCopyInto(out *AlgoOutputModel) {
	*out = *in
	if in.OutputDeliveryType != nil {
		in, out := &in.OutputDeliveryType, &out.OutputDeliveryType
		*out = new(OutputDeliveryTypes)
		**out = **in
	}
	if in.ContentType != nil {
		in, out := &in.ContentType, &out.ContentType
		*out = new(ContentTypeModel)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlgoOutputModel.
func (in *AlgoOutputModel) DeepCopy() *AlgoOutputModel {
	if in == nil {
		return nil
	}
	out := new(AlgoOutputModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlgoOutputSpec) DeepCopyInto(out *AlgoOutputSpec) {
	*out = *in
	if in.OutputDeliveryType != nil {
		in, out := &in.OutputDeliveryType, &out.OutputDeliveryType
		*out = new(OutputDeliveryTypes)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlgoOutputSpec.
func (in *AlgoOutputSpec) DeepCopy() *AlgoOutputSpec {
	if in == nil {
		return nil
	}
	out := new(AlgoOutputSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlgoParamModel) DeepCopyInto(out *AlgoParamModel) {
	*out = *in
	if in.DataType != nil {
		in, out := &in.DataType, &out.DataType
		*out = new(DataTypeModel)
		(*in).DeepCopyInto(*out)
	}
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlgoParamModel.
func (in *AlgoParamModel) DeepCopy() *AlgoParamModel {
	if in == nil {
		return nil
	}
	out := new(AlgoParamModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlgoParamSpec) DeepCopyInto(out *AlgoParamSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlgoParamSpec.
func (in *AlgoParamSpec) DeepCopy() *AlgoParamSpec {
	if in == nil {
		return nil
	}
	out := new(AlgoParamSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlgoRunnerConfig) DeepCopyInto(out *AlgoRunnerConfig) {
	*out = *in
	if in.Executor != nil {
		in, out := &in.Executor, &out.Executor
		*out = new(Executors)
		**out = **in
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make([]AlgoParamSpec, len(*in))
		copy(*out, *in)
	}
	if in.Inputs != nil {
		in, out := &in.Inputs, &out.Inputs
		*out = make([]AlgoInputSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Outputs != nil {
		in, out := &in.Outputs, &out.Outputs
		*out = make([]AlgoOutputSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Pipes != nil {
		in, out := &in.Pipes, &out.Pipes
		*out = make([]PipeModel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Topics != nil {
		in, out := &in.Topics, &out.Topics
		*out = make(map[string]TopicConfigModel, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.RetryStrategy != nil {
		in, out := &in.RetryStrategy, &out.RetryStrategy
		*out = new(TopicRetryStrategyModel)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlgoRunnerConfig.
func (in *AlgoRunnerConfig) DeepCopy() *AlgoRunnerConfig {
	if in == nil {
		return nil
	}
	out := new(AlgoRunnerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlgoSpecV1beta1) DeepCopyInto(out *AlgoSpecV1beta1) {
	*out = *in
	if in.Versions != nil {
		in, out := &in.Versions, &out.Versions
		*out = make([]AlgoVersionModel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Executor != nil {
		in, out := &in.Executor, &out.Executor
		*out = new(Executors)
		**out = **in
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make([]AlgoParamSpec, len(*in))
		copy(*out, *in)
	}
	if in.Inputs != nil {
		in, out := &in.Inputs, &out.Inputs
		*out = make([]AlgoInputSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Outputs != nil {
		in, out := &in.Outputs, &out.Outputs
		*out = make([]AlgoOutputSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlgoSpecV1beta1.
func (in *AlgoSpecV1beta1) DeepCopy() *AlgoSpecV1beta1 {
	if in == nil {
		return nil
	}
	out := new(AlgoSpecV1beta1)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlgoVersionModel) DeepCopyInto(out *AlgoVersionModel) {
	*out = *in
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(ContainerImageModel)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlgoVersionModel.
func (in *AlgoVersionModel) DeepCopy() *AlgoVersionModel {
	if in == nil {
		return nil
	}
	out := new(AlgoVersionModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoScalingSpec) DeepCopyInto(out *AutoScalingSpec) {
	*out = *in
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make([]ScaleMetricModel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoScalingSpec.
func (in *AutoScalingSpec) DeepCopy() *AutoScalingSpec {
	if in == nil {
		return nil
	}
	out := new(AutoScalingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentPodStatus) DeepCopyInto(out *ComponentPodStatus) {
	*out = *in
	if in.ContainerStatuses != nil {
		in, out := &in.ContainerStatuses, &out.ContainerStatuses
		*out = make([]v1.ContainerStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentPodStatus.
func (in *ComponentPodStatus) DeepCopy() *ComponentPodStatus {
	if in == nil {
		return nil
	}
	out := new(ComponentPodStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentStatus) DeepCopyInto(out *ComponentStatus) {
	*out = *in
	if in.ComponentType != nil {
		in, out := &in.ComponentType, &out.ComponentType
		*out = new(ComponentTypes)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentStatus.
func (in *ComponentStatus) DeepCopy() *ComponentStatus {
	if in == nil {
		return nil
	}
	out := new(ComponentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMountModel) DeepCopyInto(out *ConfigMountModel) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMountModel.
func (in *ConfigMountModel) DeepCopy() *ConfigMountModel {
	if in == nil {
		return nil
	}
	out := new(ConfigMountModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerImageModel) DeepCopyInto(out *ContainerImageModel) {
	*out = *in
	if in.ImagePullPolicy != nil {
		in, out := &in.ImagePullPolicy, &out.ImagePullPolicy
		*out = new(ImagePullPolicies)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerImageModel.
func (in *ContainerImageModel) DeepCopy() *ContainerImageModel {
	if in == nil {
		return nil
	}
	out := new(ContainerImageModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContentTypeModel) DeepCopyInto(out *ContentTypeModel) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContentTypeModel.
func (in *ContentTypeModel) DeepCopy() *ContentTypeModel {
	if in == nil {
		return nil
	}
	out := new(ContentTypeModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomResourceRefV1beta1) DeepCopyInto(out *CustomResourceRefV1beta1) {
	*out = *in
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomResourceRefV1beta1.
func (in *CustomResourceRefV1beta1) DeepCopy() *CustomResourceRefV1beta1 {
	if in == nil {
		return nil
	}
	out := new(CustomResourceRefV1beta1)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataConnector) DeepCopyInto(out *DataConnector) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataConnector.
func (in *DataConnector) DeepCopy() *DataConnector {
	if in == nil {
		return nil
	}
	out := new(DataConnector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataConnector) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataConnectorDeploymentV1beta1) DeepCopyInto(out *DataConnectorDeploymentV1beta1) {
	*out = *in
	if in.DataConnectorRef != nil {
		in, out := &in.DataConnectorRef, &out.DataConnectorRef
		*out = new(CustomResourceRefV1beta1)
		(*in).DeepCopyInto(*out)
	}
	if in.Topics != nil {
		in, out := &in.Topics, &out.Topics
		*out = make([]TopicConfigModel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make([]DataConnectorOptionModel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourceRequirementsV1)
		(*in).DeepCopyInto(*out)
	}
	if in.Autoscaling != nil {
		in, out := &in.Autoscaling, &out.Autoscaling
		*out = new(AutoScalingSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.LivenessProbe != nil {
		in, out := &in.LivenessProbe, &out.LivenessProbe
		*out = new(ProbeV1)
		(*in).DeepCopyInto(*out)
	}
	if in.ReadinessProbe != nil {
		in, out := &in.ReadinessProbe, &out.ReadinessProbe
		*out = new(ProbeV1)
		(*in).DeepCopyInto(*out)
	}
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(DataConnectorSpecV1beta1)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataConnectorDeploymentV1beta1.
func (in *DataConnectorDeploymentV1beta1) DeepCopy() *DataConnectorDeploymentV1beta1 {
	if in == nil {
		return nil
	}
	out := new(DataConnectorDeploymentV1beta1)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataConnectorList) DeepCopyInto(out *DataConnectorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DataConnector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataConnectorList.
func (in *DataConnectorList) DeepCopy() *DataConnectorList {
	if in == nil {
		return nil
	}
	out := new(DataConnectorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataConnectorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataConnectorOptionModel) DeepCopyInto(out *DataConnectorOptionModel) {
	*out = *in
	if in.DataType != nil {
		in, out := &in.DataType, &out.DataType
		*out = new(DataTypeModel)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataConnectorOptionModel.
func (in *DataConnectorOptionModel) DeepCopy() *DataConnectorOptionModel {
	if in == nil {
		return nil
	}
	out := new(DataConnectorOptionModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataConnectorSpecV1beta1) DeepCopyInto(out *DataConnectorSpecV1beta1) {
	*out = *in
	if in.DataConnectorType != nil {
		in, out := &in.DataConnectorType, &out.DataConnectorType
		*out = new(DataConnectorTypes)
		**out = **in
	}
	if in.Versions != nil {
		in, out := &in.Versions, &out.Versions
		*out = make([]DataConnectorVersionModel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make([]DataConnectorOptionModel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataConnectorSpecV1beta1.
func (in *DataConnectorSpecV1beta1) DeepCopy() *DataConnectorSpecV1beta1 {
	if in == nil {
		return nil
	}
	out := new(DataConnectorSpecV1beta1)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataConnectorVersionModel) DeepCopyInto(out *DataConnectorVersionModel) {
	*out = *in
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(ContainerImageModel)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataConnectorVersionModel.
func (in *DataConnectorVersionModel) DeepCopy() *DataConnectorVersionModel {
	if in == nil {
		return nil
	}
	out := new(DataConnectorVersionModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataTypeModel) DeepCopyInto(out *DataTypeModel) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(DataTypes)
		**out = **in
	}
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataTypeModel.
func (in *DataTypeModel) DeepCopy() *DataTypeModel {
	if in == nil {
		return nil
	}
	out := new(DataTypeModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeepCopyTime.
func (in *DeepCopyTime) DeepCopy() *DeepCopyTime {
	if in == nil {
		return nil
	}
	out := new(DeepCopyTime)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentStatusMessage) DeepCopyInto(out *DeploymentStatusMessage) {
	*out = *in
	if in.ComponentStatus != nil {
		in, out := &in.ComponentStatus, &out.ComponentStatus
		*out = make([]ComponentStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PodStatus != nil {
		in, out := &in.PodStatus, &out.PodStatus
		*out = make([]ComponentPodStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentStatusMessage.
func (in *DeploymentStatusMessage) DeepCopy() *DeploymentStatusMessage {
	if in == nil {
		return nil
	}
	out := new(DeploymentStatusMessage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointKafkaConfig) DeepCopyInto(out *EndpointKafkaConfig) {
	*out = *in
	if in.Brokers != nil {
		in, out := &in.Brokers, &out.Brokers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointKafkaConfig.
func (in *EndpointKafkaConfig) DeepCopy() *EndpointKafkaConfig {
	if in == nil {
		return nil
	}
	out := new(EndpointKafkaConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointPathModel) DeepCopyInto(out *EndpointPathModel) {
	*out = *in
	if in.EndpointType != nil {
		in, out := &in.EndpointType, &out.EndpointType
		*out = new(EndpointTypes)
		**out = **in
	}
	if in.MessageDataType != nil {
		in, out := &in.MessageDataType, &out.MessageDataType
		*out = new(MessageDataTypes)
		**out = **in
	}
	if in.ContentType != nil {
		in, out := &in.ContentType, &out.ContentType
		*out = new(ContentTypeModel)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointPathModel.
func (in *EndpointPathModel) DeepCopy() *EndpointPathModel {
	if in == nil {
		return nil
	}
	out := new(EndpointPathModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointPathSpec) DeepCopyInto(out *EndpointPathSpec) {
	*out = *in
	if in.EndpointType != nil {
		in, out := &in.EndpointType, &out.EndpointType
		*out = new(EndpointTypes)
		**out = **in
	}
	if in.MessageDataType != nil {
		in, out := &in.MessageDataType, &out.MessageDataType
		*out = new(MessageDataTypes)
		**out = **in
	}
	if in.Topic != nil {
		in, out := &in.Topic, &out.Topic
		*out = new(TopicConfigModel)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointPathSpec.
func (in *EndpointPathSpec) DeepCopy() *EndpointPathSpec {
	if in == nil {
		return nil
	}
	out := new(EndpointPathSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointProducerConfig) DeepCopyInto(out *EndpointProducerConfig) {
	*out = *in
	if in.Cb != nil {
		in, out := &in.Cb, &out.Cb
		*out = new(ProducerCircuitBreaker)
		**out = **in
	}
	if in.Resend != nil {
		in, out := &in.Resend, &out.Resend
		*out = new(ProducerResend)
		**out = **in
	}
	if in.Wal != nil {
		in, out := &in.Wal, &out.Wal
		*out = new(ProducerWal)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointProducerConfig.
func (in *EndpointProducerConfig) DeepCopy() *EndpointProducerConfig {
	if in == nil {
		return nil
	}
	out := new(EndpointProducerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointServerConfig) DeepCopyInto(out *EndpointServerConfig) {
	*out = *in
	if in.Http != nil {
		in, out := &in.Http, &out.Http
		*out = new(EndpointServerListen)
		**out = **in
	}
	if in.Grpc != nil {
		in, out := &in.Grpc, &out.Grpc
		*out = new(EndpointServerListen)
		**out = **in
	}
	if in.Monitoring != nil {
		in, out := &in.Monitoring, &out.Monitoring
		*out = new(EndpointServerListen)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointServerConfig.
func (in *EndpointServerConfig) DeepCopy() *EndpointServerConfig {
	if in == nil {
		return nil
	}
	out := new(EndpointServerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointServerListen) DeepCopyInto(out *EndpointServerListen) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointServerListen.
func (in *EndpointServerListen) DeepCopy() *EndpointServerListen {
	if in == nil {
		return nil
	}
	out := new(EndpointServerListen)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointSpec) DeepCopyInto(out *EndpointSpec) {
	*out = *in
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(ContainerImageModel)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourceRequirementsV1)
		(*in).DeepCopyInto(*out)
	}
	if in.Autoscaling != nil {
		in, out := &in.Autoscaling, &out.Autoscaling
		*out = new(AutoScalingSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Paths != nil {
		in, out := &in.Paths, &out.Paths
		*out = make([]EndpointPathSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Server != nil {
		in, out := &in.Server, &out.Server
		*out = new(EndpointServerConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Producer != nil {
		in, out := &in.Producer, &out.Producer
		*out = new(EndpointProducerConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Kafka != nil {
		in, out := &in.Kafka, &out.Kafka
		*out = new(EndpointKafkaConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.LivenessProbe != nil {
		in, out := &in.LivenessProbe, &out.LivenessProbe
		*out = new(ProbeV1)
		(*in).DeepCopyInto(*out)
	}
	if in.ReadinessProbe != nil {
		in, out := &in.ReadinessProbe, &out.ReadinessProbe
		*out = new(ProbeV1)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointSpec.
func (in *EndpointSpec) DeepCopy() *EndpointSpec {
	if in == nil {
		return nil
	}
	out := new(EndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventHookSpec) DeepCopyInto(out *EventHookSpec) {
	*out = *in
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(ContainerImageModel)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourceRequirementsV1)
		(*in).DeepCopyInto(*out)
	}
	if in.Autoscaling != nil {
		in, out := &in.Autoscaling, &out.Autoscaling
		*out = new(AutoScalingSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.WebHooks != nil {
		in, out := &in.WebHooks, &out.WebHooks
		*out = make([]WebHookModel, len(*in))
		copy(*out, *in)
	}
	if in.LivenessProbe != nil {
		in, out := &in.LivenessProbe, &out.LivenessProbe
		*out = new(ProbeV1)
		(*in).DeepCopyInto(*out)
	}
	if in.ReadinessProbe != nil {
		in, out := &in.ReadinessProbe, &out.ReadinessProbe
		*out = new(ProbeV1)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventHookSpec.
func (in *EventHookSpec) DeepCopy() *EventHookSpec {
	if in == nil {
		return nil
	}
	out := new(EventHookSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecActionV1) DeepCopyInto(out *ExecActionV1) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecActionV1.
func (in *ExecActionV1) DeepCopy() *ExecActionV1 {
	if in == nil {
		return nil
	}
	out := new(ExecActionV1)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HttpGetActionV1) DeepCopyInto(out *HttpGetActionV1) {
	*out = *in
	if in.HttpHeaders != nil {
		in, out := &in.HttpHeaders, &out.HttpHeaders
		*out = make([]HttpHeaderV1, len(*in))
		copy(*out, *in)
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(Int32OrStringV1)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HttpGetActionV1.
func (in *HttpGetActionV1) DeepCopy() *HttpGetActionV1 {
	if in == nil {
		return nil
	}
	out := new(HttpGetActionV1)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HttpHeaderV1) DeepCopyInto(out *HttpHeaderV1) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HttpHeaderV1.
func (in *HttpHeaderV1) DeepCopy() *HttpHeaderV1 {
	if in == nil {
		return nil
	}
	out := new(HttpHeaderV1)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Int32OrStringV1) DeepCopyInto(out *Int32OrStringV1) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Int32OrStringV1.
func (in *Int32OrStringV1) DeepCopy() *Int32OrStringV1 {
	if in == nil {
		return nil
	}
	out := new(Int32OrStringV1)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotifMessage) DeepCopyInto(out *NotifMessage) {
	*out = *in
	in.MessageTimestamp = out.MessageTimestamp
	if in.Level != nil {
		in, out := &in.Level, &out.Level
		*out = new(LogLevels)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(NotifTypes)
		**out = **in
	}
	if in.DeploymentStatusMessage != nil {
		in, out := &in.DeploymentStatusMessage, &out.DeploymentStatusMessage
		*out = new(DeploymentStatusMessage)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotifMessage.
func (in *NotifMessage) DeepCopy() *NotifMessage {
	if in == nil {
		return nil
	}
	out := new(NotifMessage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipeModel) DeepCopyInto(out *PipeModel) {
	*out = *in
	if in.SourceComponentType != nil {
		in, out := &in.SourceComponentType, &out.SourceComponentType
		*out = new(ComponentTypes)
		**out = **in
	}
	if in.SourceOutputMessageDataType != nil {
		in, out := &in.SourceOutputMessageDataType, &out.SourceOutputMessageDataType
		*out = new(MessageDataTypes)
		**out = **in
	}
	if in.DestComponentType != nil {
		in, out := &in.DestComponentType, &out.DestComponentType
		*out = new(ComponentTypes)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipeModel.
func (in *PipeModel) DeepCopy() *PipeModel {
	if in == nil {
		return nil
	}
	out := new(PipeModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineDeployment) DeepCopyInto(out *PipelineDeployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineDeployment.
func (in *PipelineDeployment) DeepCopy() *PipelineDeployment {
	if in == nil {
		return nil
	}
	out := new(PipelineDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PipelineDeployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineDeploymentList) DeepCopyInto(out *PipelineDeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PipelineDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineDeploymentList.
func (in *PipelineDeploymentList) DeepCopy() *PipelineDeploymentList {
	if in == nil {
		return nil
	}
	out := new(PipelineDeploymentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PipelineDeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineDeploymentSpecV1beta1) DeepCopyInto(out *PipelineDeploymentSpecV1beta1) {
	*out = *in
	if in.Endpoint != nil {
		in, out := &in.Endpoint, &out.Endpoint
		*out = new(EndpointSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Algos != nil {
		in, out := &in.Algos, &out.Algos
		*out = make([]AlgoDeploymentV1beta1, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DataConnectors != nil {
		in, out := &in.DataConnectors, &out.DataConnectors
		*out = make([]DataConnectorDeploymentV1beta1, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EventHook != nil {
		in, out := &in.EventHook, &out.EventHook
		*out = new(EventHookSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Pipes != nil {
		in, out := &in.Pipes, &out.Pipes
		*out = make([]PipeModel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineDeploymentSpecV1beta1.
func (in *PipelineDeploymentSpecV1beta1) DeepCopy() *PipelineDeploymentSpecV1beta1 {
	if in == nil {
		return nil
	}
	out := new(PipelineDeploymentSpecV1beta1)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineDeploymentStatus) DeepCopyInto(out *PipelineDeploymentStatus) {
	*out = *in
	if in.ComponentStatuses != nil {
		in, out := &in.ComponentStatuses, &out.ComponentStatuses
		*out = make([]ComponentStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PodStatuses != nil {
		in, out := &in.PodStatuses, &out.PodStatuses
		*out = make([]ComponentPodStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineDeploymentStatus.
func (in *PipelineDeploymentStatus) DeepCopy() *PipelineDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(PipelineDeploymentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProbeV1) DeepCopyInto(out *ProbeV1) {
	*out = *in
	if in.Exec != nil {
		in, out := &in.Exec, &out.Exec
		*out = new(ExecActionV1)
		(*in).DeepCopyInto(*out)
	}
	if in.HttpGet != nil {
		in, out := &in.HttpGet, &out.HttpGet
		*out = new(HttpGetActionV1)
		(*in).DeepCopyInto(*out)
	}
	if in.TcpSocket != nil {
		in, out := &in.TcpSocket, &out.TcpSocket
		*out = new(TcpSocketActionV1)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProbeV1.
func (in *ProbeV1) DeepCopy() *ProbeV1 {
	if in == nil {
		return nil
	}
	out := new(ProbeV1)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProducerCircuitBreaker) DeepCopyInto(out *ProducerCircuitBreaker) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProducerCircuitBreaker.
func (in *ProducerCircuitBreaker) DeepCopy() *ProducerCircuitBreaker {
	if in == nil {
		return nil
	}
	out := new(ProducerCircuitBreaker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProducerResend) DeepCopyInto(out *ProducerResend) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProducerResend.
func (in *ProducerResend) DeepCopy() *ProducerResend {
	if in == nil {
		return nil
	}
	out := new(ProducerResend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProducerWal) DeepCopyInto(out *ProducerWal) {
	*out = *in
	if in.AlwaysTopics != nil {
		in, out := &in.AlwaysTopics, &out.AlwaysTopics
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DisableTopics != nil {
		in, out := &in.DisableTopics, &out.DisableTopics
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProducerWal.
func (in *ProducerWal) DeepCopy() *ProducerWal {
	if in == nil {
		return nil
	}
	out := new(ProducerWal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRequirementsV1) DeepCopyInto(out *ResourceRequirementsV1) {
	*out = *in
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Requests != nil {
		in, out := &in.Requests, &out.Requests
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRequirementsV1.
func (in *ResourceRequirementsV1) DeepCopy() *ResourceRequirementsV1 {
	if in == nil {
		return nil
	}
	out := new(ResourceRequirementsV1)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleMetricModel) DeepCopyInto(out *ScaleMetricModel) {
	*out = *in
	if in.SourceType != nil {
		in, out := &in.SourceType, &out.SourceType
		*out = new(MetricSourceTypes)
		**out = **in
	}
	if in.TargetType != nil {
		in, out := &in.TargetType, &out.TargetType
		*out = new(MetricTargetTypes)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleMetricModel.
func (in *ScaleMetricModel) DeepCopy() *ScaleMetricModel {
	if in == nil {
		return nil
	}
	out := new(ScaleMetricModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TcpSocketActionV1) DeepCopyInto(out *TcpSocketActionV1) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(Int32OrStringV1)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TcpSocketActionV1.
func (in *TcpSocketActionV1) DeepCopy() *TcpSocketActionV1 {
	if in == nil {
		return nil
	}
	out := new(TcpSocketActionV1)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopicConfigModel) DeepCopyInto(out *TopicConfigModel) {
	*out = *in
	if in.TopicParams != nil {
		in, out := &in.TopicParams, &out.TopicParams
		*out = make([]TopicParamModel, len(*in))
		copy(*out, *in)
	}
	if in.RetryStrategy != nil {
		in, out := &in.RetryStrategy, &out.RetryStrategy
		*out = new(TopicRetryStrategyModel)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopicConfigModel.
func (in *TopicConfigModel) DeepCopy() *TopicConfigModel {
	if in == nil {
		return nil
	}
	out := new(TopicConfigModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopicParamModel) DeepCopyInto(out *TopicParamModel) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopicParamModel.
func (in *TopicParamModel) DeepCopy() *TopicParamModel {
	if in == nil {
		return nil
	}
	out := new(TopicParamModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopicRetryStepModel) DeepCopyInto(out *TopicRetryStepModel) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopicRetryStepModel.
func (in *TopicRetryStepModel) DeepCopy() *TopicRetryStepModel {
	if in == nil {
		return nil
	}
	out := new(TopicRetryStepModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopicRetryStrategyModel) DeepCopyInto(out *TopicRetryStrategyModel) {
	*out = *in
	if in.Strategy != nil {
		in, out := &in.Strategy, &out.Strategy
		*out = new(RetryStrategies)
		**out = **in
	}
	if in.Steps != nil {
		in, out := &in.Steps, &out.Steps
		*out = make([]TopicRetryStepModel, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopicRetryStrategyModel.
func (in *TopicRetryStrategyModel) DeepCopy() *TopicRetryStrategyModel {
	if in == nil {
		return nil
	}
	out := new(TopicRetryStrategyModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebHookModel) DeepCopyInto(out *WebHookModel) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebHookModel.
func (in *WebHookModel) DeepCopy() *WebHookModel {
	if in == nil {
		return nil
	}
	out := new(WebHookModel)
	in.DeepCopyInto(out)
	return out
}
