/*
 * Algo.Run API 1.0
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0
 * Contact: support@algohub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
)

type AlgoPodStatus struct {
	AlgoOwnerName string `json:"algoOwnerName,omitempty"`

	AlgoName string `json:"algoName,omitempty"`

	AlgoVersionTag string `json:"algoVersionTag,omitempty"`

	AlgoIndex int32 `json:"algoIndex,omitempty"`

	Name string `json:"name,omitempty"`

	Status string `json:"status,omitempty"`

	Restarts int32 `json:"restarts,omitempty"`

	Ip string `json:"ip,omitempty"`

	Node string `json:"node,omitempty"`

	ContainerStatuses []corev1.ContainerStatus `json:"containerStatuses,omitempty"`

	CreatedTimestamp string `json:"createdTimestamp,omitempty"`
}
