/*
 * Algo.Run API 1.0
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0
 * Contact: support@algohub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1alpha1

type DeploymentStatusMessage struct {

	DeploymentOwnerUserName string `json:"deploymentOwnerUserName,omitempty"`

	DeploymentName string `json:"deploymentName,omitempty"`

	Status string `json:"status,omitempty"`

	AlgoDeploymentStatus *AlgoDeploymentStatus `json:"algoDeploymentStatus,omitempty"`

	AlgoPodStatus *AlgoPodStatus `json:"algoPodStatus,omitempty"`
}
