/*
 * Algo.Run API 1.0
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0
 * Contact: support@algohub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1alpha1

type EndpointPathModel struct {

	Name string `json:"name,omitempty"`

	IsDefault bool `json:"isDefault,omitempty"`

	Description string `json:"description,omitempty"`

	ConnectionString string `json:"connectionString,omitempty"`

	EndpointType string `json:"endpointType,omitempty"`

	MessageDataType string `json:"messageDataType,omitempty"`

	ContentType *ContentTypeModel `json:"contentType,omitempty"`
}
