/*
 * Algo.Run API 1.0
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0
 * Contact: support@algohub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1alpha1

type EndpointProducerConfig struct {

	Cb *ProducerCircuitBreaker `json:"cb,omitempty"`

	Resend *ProducerResend `json:"resend,omitempty"`

	Wal *ProducerWal `json:"wal,omitempty"`
}
