/*
 * Algo.Run API 1.0
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0
 * Contact: support@algohub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1alpha1

type EndpointStatusMessage struct {

	EndpointOwnerUserName string `json:"endpointOwnerUserName,omitempty"`

	EndpointName string `json:"endpointName,omitempty"`

	Status string `json:"status,omitempty"`

	AlgoDeploymentStatus *AlgoDeploymentStatus `json:"algoDeploymentStatus,omitempty"`

	AlgoPodStatus *AlgoPodStatus `json:"algoPodStatus,omitempty"`
}
