/*
 * Algo.Run API 1.0
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0
 * Contact: support@algohub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1alpha1

type HookConfig struct {

	ImageRepository string `json:"imageRepository,omitempty"`

	ImageTag string `json:"imageTag,omitempty"`

	Instances int32 `json:"instances,omitempty"`

	WebHooks []WebHookModel `json:"webHooks,omitempty"`
}
