/*
 * Algo.Run API 1.0
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0
 * Contact: support@algohub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1alpha1

type MediaTypeModel struct {

	Title string `json:"title,omitempty"`

	Name string `json:"name,omitempty"`

	GroupName string `json:"groupName,omitempty"`

	SubTypeName string `json:"subTypeName,omitempty"`

	FileExtension string `json:"fileExtension,omitempty"`

	Encoding string `json:"encoding,omitempty"`

	Rfc string `json:"rfc,omitempty"`

	RfcUrl string `json:"rfcUrl,omitempty"`

	Url string `json:"url,omitempty"`

	IconClass string `json:"iconClass,omitempty"`
}
