/*
 * Algo.Run API 1.0
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0
 * Contact: support@algohub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1alpha1

type ProducerCircuitBreaker struct {

	Interval int32 `json:"interval,omitempty"`

	Timeout string `json:"timeout,omitempty"`

	Fails int32 `json:"fails,omitempty"`

	Requests int32 `json:"requests,omitempty"`
}
