/*
 * Algo.Run API 1.0
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0
 * Contact: support@algohub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1alpha1

type ResourceModel struct {
	MemoryRequestBytes int64 `json:"memoryRequestBytes,omitempty"`

	MemoryLimitBytes int64 `json:"memoryLimitBytes,omitempty"`

	CpuRequestUnits float64 `json:"cpuRequestUnits,omitempty"`

	CpuLimitUnits float64 `json:"cpuLimitUnits,omitempty"`

	GpuLimitUnits float64 `json:"gpuLimitUnits,omitempty"`

	Instances int32 `json:"instances,omitempty"`

	AutoScale bool `json:"autoScale,omitempty"`

	MinInstances int32 `json:"minInstances,omitempty"`

	MaxInstances int32 `json:"maxInstances,omitempty"`

	ScaleMetrics []ScaleMetricModel `json:"scaleMetrics,omitempty"`
}
