/*
 * Algo.Run API 1.0
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0
 * Contact: support@algohub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1alpha1

type ScaleMetricModel struct {

	SourceType string `json:"sourceType,omitempty"`

	Name string `json:"name,omitempty"`

	Selector string `json:"selector,omitempty"`

	TargetAverageUtilization int32 `json:"targetAverageUtilization,omitempty"`

	TargetAverageValue float64 `json:"targetAverageValue,omitempty"`
}
