package v1alpha1

import (
	time "time"
)

type DeepCopyTime time.Time

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeepCopyTime) DeepCopyInto(out *DeepCopyTime) {
	*out = *in
	return
}
