/*
 * Algo.Run API 1.0
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0
 * Contact: support@algohub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1alpha1

type TopicConfigModel struct {

	PipeType string `json:"pipeType,omitempty"`

	EndpointConnectorOutputName string `json:"endpointConnectorOutputName,omitempty"`

	PipelineDataSourceName string `json:"pipelineDataSourceName,omitempty"`

	PipelineDataSourceIndex int32 `json:"pipelineDataSourceIndex,omitempty"`

	AlgoOwnerName string `json:"algoOwnerName,omitempty"`

	AlgoName string `json:"algoName,omitempty"`

	AlgoIndex int32 `json:"algoIndex,omitempty"`

	AlgoOutputName string `json:"algoOutputName,omitempty"`

	TopicAutoName bool `json:"topicAutoName,omitempty"`

	TopicName string `json:"topicName,omitempty"`

	TopicAutoPartition bool `json:"topicAutoPartition,omitempty"`

	TopicPartitions int32 `json:"topicPartitions,omitempty"`

	TopicReplicationFactor int32 `json:"topicReplicationFactor,omitempty"`

	TopicParams []TopicParamModel `json:"topicParams,omitempty"`
}
