/*
 * Algo.Run API 1.0
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0
 * Contact: support@algohub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package v1alpha1

type WebHookModel struct {

	EndpointOwnerUserName string `json:"endpointOwnerUserName,omitempty"`

	EndpointName string `json:"endpointName,omitempty"`

	PipelineHookInputName string `json:"pipelineHookInputName,omitempty"`

	WebHookUrl string `json:"webHookUrl,omitempty"`

	HttpVerb string `json:"httpVerb,omitempty"`

	HttpHeaders string `json:"httpHeaders,omitempty"`
}
