// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlgoConfig) DeepCopyInto(out *AlgoConfig) {
	*out = *in
	if in.AlgoParams != nil {
		in, out := &in.AlgoParams, &out.AlgoParams
		*out = make([]AlgoParamModel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Inputs != nil {
		in, out := &in.Inputs, &out.Inputs
		*out = make([]AlgoInputModel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Outputs != nil {
		in, out := &in.Outputs, &out.Outputs
		*out = make([]AlgoOutputModel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlgoConfig.
func (in *AlgoConfig) DeepCopy() *AlgoConfig {
	if in == nil {
		return nil
	}
	out := new(AlgoConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlgoInputModel) DeepCopyInto(out *AlgoInputModel) {
	*out = *in
	if in.MediaTypes != nil {
		in, out := &in.MediaTypes, &out.MediaTypes
		*out = make([]MediaTypeModel, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlgoInputModel.
func (in *AlgoInputModel) DeepCopy() *AlgoInputModel {
	if in == nil {
		return nil
	}
	out := new(AlgoInputModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlgoOutputModel) DeepCopyInto(out *AlgoOutputModel) {
	*out = *in
	if in.MediaType != nil {
		in, out := &in.MediaType, &out.MediaType
		*out = new(MediaTypeModel)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlgoOutputModel.
func (in *AlgoOutputModel) DeepCopy() *AlgoOutputModel {
	if in == nil {
		return nil
	}
	out := new(AlgoOutputModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlgoParamModel) DeepCopyInto(out *AlgoParamModel) {
	*out = *in
	if in.DataType != nil {
		in, out := &in.DataType, &out.DataType
		*out = new(DataTypeModel)
		**out = **in
	}
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make([]DataTypeOptionModel, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlgoParamModel.
func (in *AlgoParamModel) DeepCopy() *AlgoParamModel {
	if in == nil {
		return nil
	}
	out := new(AlgoParamModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataConnectorModel) DeepCopyInto(out *DataConnectorModel) {
	*out = *in
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make([]DataConnectorOptionModel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataConnectorModel.
func (in *DataConnectorModel) DeepCopy() *DataConnectorModel {
	if in == nil {
		return nil
	}
	out := new(DataConnectorModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataConnectorOptionModel) DeepCopyInto(out *DataConnectorOptionModel) {
	*out = *in
	if in.DataType != nil {
		in, out := &in.DataType, &out.DataType
		*out = new(DataTypeModel)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataConnectorOptionModel.
func (in *DataConnectorOptionModel) DeepCopy() *DataConnectorOptionModel {
	if in == nil {
		return nil
	}
	out := new(DataConnectorOptionModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataTypeModel) DeepCopyInto(out *DataTypeModel) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataTypeModel.
func (in *DataTypeModel) DeepCopy() *DataTypeModel {
	if in == nil {
		return nil
	}
	out := new(DataTypeModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataTypeOptionModel) DeepCopyInto(out *DataTypeOptionModel) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataTypeOptionModel.
func (in *DataTypeOptionModel) DeepCopy() *DataTypeOptionModel {
	if in == nil {
		return nil
	}
	out := new(DataTypeOptionModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Endpoint) DeepCopyInto(out *Endpoint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Endpoint.
func (in *Endpoint) DeepCopy() *Endpoint {
	if in == nil {
		return nil
	}
	out := new(Endpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Endpoint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointDeployCmd) DeepCopyInto(out *EndpointDeployCmd) {
	*out = *in
	if in.AlgoConfigs != nil {
		in, out := &in.AlgoConfigs, &out.AlgoConfigs
		*out = make([]AlgoConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TopicConfigs != nil {
		in, out := &in.TopicConfigs, &out.TopicConfigs
		*out = make([]TopicConfigModel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Pipes != nil {
		in, out := &in.Pipes, &out.Pipes
		*out = make([]PipeModel, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointDeployCmd.
func (in *EndpointDeployCmd) DeepCopy() *EndpointDeployCmd {
	if in == nil {
		return nil
	}
	out := new(EndpointDeployCmd)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointList) DeepCopyInto(out *EndpointList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Endpoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointList.
func (in *EndpointList) DeepCopy() *EndpointList {
	if in == nil {
		return nil
	}
	out := new(EndpointList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EndpointList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointSpec) DeepCopyInto(out *EndpointSpec) {
	*out = *in
	in.EndpointConfig.DeepCopyInto(&out.EndpointConfig)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointSpec.
func (in *EndpointSpec) DeepCopy() *EndpointSpec {
	if in == nil {
		return nil
	}
	out := new(EndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointStatus) DeepCopyInto(out *EndpointStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointStatus.
func (in *EndpointStatus) DeepCopy() *EndpointStatus {
	if in == nil {
		return nil
	}
	out := new(EndpointStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointStopCmd) DeepCopyInto(out *EndpointStopCmd) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointStopCmd.
func (in *EndpointStopCmd) DeepCopy() *EndpointStopCmd {
	if in == nil {
		return nil
	}
	out := new(EndpointStopCmd)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MediaTypeModel) DeepCopyInto(out *MediaTypeModel) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MediaTypeModel.
func (in *MediaTypeModel) DeepCopy() *MediaTypeModel {
	if in == nil {
		return nil
	}
	out := new(MediaTypeModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrchestratorCommand) DeepCopyInto(out *OrchestratorCommand) {
	*out = *in
	if in.EndpointDeployCmd != nil {
		in, out := &in.EndpointDeployCmd, &out.EndpointDeployCmd
		*out = new(EndpointDeployCmd)
		(*in).DeepCopyInto(*out)
	}
	if in.EndpointStopCmd != nil {
		in, out := &in.EndpointStopCmd, &out.EndpointStopCmd
		*out = new(EndpointStopCmd)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrchestratorCommand.
func (in *OrchestratorCommand) DeepCopy() *OrchestratorCommand {
	if in == nil {
		return nil
	}
	out := new(OrchestratorCommand)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipeModel) DeepCopyInto(out *PipeModel) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipeModel.
func (in *PipeModel) DeepCopy() *PipeModel {
	if in == nil {
		return nil
	}
	out := new(PipeModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelineDataConnectorModel) DeepCopyInto(out *PipelineDataConnectorModel) {
	*out = *in
	if in.DataConnector != nil {
		in, out := &in.DataConnector, &out.DataConnector
		*out = new(DataConnectorModel)
		(*in).DeepCopyInto(*out)
	}
	if in.OptionOverrides != nil {
		in, out := &in.OptionOverrides, &out.OptionOverrides
		*out = make([]DataConnectorOptionModel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelineDataConnectorModel.
func (in *PipelineDataConnectorModel) DeepCopy() *PipelineDataConnectorModel {
	if in == nil {
		return nil
	}
	out := new(PipelineDataConnectorModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerConfig) DeepCopyInto(out *RunnerConfig) {
	*out = *in
	if in.AlgoParams != nil {
		in, out := &in.AlgoParams, &out.AlgoParams
		*out = make([]AlgoParamModel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Inputs != nil {
		in, out := &in.Inputs, &out.Inputs
		*out = make([]AlgoInputModel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Outputs != nil {
		in, out := &in.Outputs, &out.Outputs
		*out = make([]AlgoOutputModel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Pipes != nil {
		in, out := &in.Pipes, &out.Pipes
		*out = make([]PipeModel, len(*in))
		copy(*out, *in)
	}
	if in.TopicConfigs != nil {
		in, out := &in.TopicConfigs, &out.TopicConfigs
		*out = make([]TopicConfigModel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerConfig.
func (in *RunnerConfig) DeepCopy() *RunnerConfig {
	if in == nil {
		return nil
	}
	out := new(RunnerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopicConfigModel) DeepCopyInto(out *TopicConfigModel) {
	*out = *in
	if in.TopicParams != nil {
		in, out := &in.TopicParams, &out.TopicParams
		*out = make([]TopicParamModel, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopicConfigModel.
func (in *TopicConfigModel) DeepCopy() *TopicConfigModel {
	if in == nil {
		return nil
	}
	out := new(TopicConfigModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopicParamModel) DeepCopyInto(out *TopicParamModel) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopicParamModel.
func (in *TopicParamModel) DeepCopy() *TopicParamModel {
	if in == nil {
		return nil
	}
	out := new(TopicParamModel)
	in.DeepCopyInto(out)
	return out
}
