// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"endpoint-operator/pkg/apis/algo/v1alpha1.Endpoint":       schema_pkg_apis_algo_v1alpha1_Endpoint(ref),
		"endpoint-operator/pkg/apis/algo/v1alpha1.EndpointSpec":   schema_pkg_apis_algo_v1alpha1_EndpointSpec(ref),
		"endpoint-operator/pkg/apis/algo/v1alpha1.EndpointStatus": schema_pkg_apis_algo_v1alpha1_EndpointStatus(ref),
	}
}

func schema_pkg_apis_algo_v1alpha1_Endpoint(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Endpoint is the Schema for the endpoints API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("endpoint-operator/pkg/apis/algo/v1alpha1.EndpointSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("endpoint-operator/pkg/apis/algo/v1alpha1.EndpointStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"endpoint-operator/pkg/apis/algo/v1alpha1.EndpointSpec", "endpoint-operator/pkg/apis/algo/v1alpha1.EndpointStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_algo_v1alpha1_EndpointSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "EndpointSpec defines the desired state of Endpoint",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_algo_v1alpha1_EndpointStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "EndpointStatus defines the observed state of Endpoint",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
