// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"pipeline-operator/pkg/apis/algo/v1alpha1.PipelineDeployment":       schema_pkg_apis_algo_v1alpha1_PipelineDeployment(ref),
		"pipeline-operator/pkg/apis/algo/v1alpha1.PipelineDeploymentSpec":   schema_pkg_apis_algo_v1alpha1_PipelineDeploymentSpec(ref),
		"pipeline-operator/pkg/apis/algo/v1alpha1.PipelineDeploymentStatus": schema_pkg_apis_algo_v1alpha1_PipelineDeploymentStatus(ref),
	}
}

func schema_pkg_apis_algo_v1alpha1_PipelineDeployment(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "PipelineDeployment is the Schema for the PipelineDeployments API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("pipeline-operator/pkg/apis/algo/v1alpha1.PipelineDeploymentSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("pipeline-operator/pkg/apis/algo/v1alpha1.PipelineDeploymentStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta", "pipeline-operator/pkg/apis/algo/v1alpha1.PipelineDeploymentSpec", "pipeline-operator/pkg/apis/algo/v1alpha1.PipelineDeploymentStatus"},
	}
}

func schema_pkg_apis_algo_v1alpha1_PipelineDeploymentSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "PipelineDeploymentSpec defines the desired state of the PipelineDeployment",
				Properties: map[string]spec.Schema{
					"imagePullPolicy": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"kafkaBrokers": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"pipelineSpec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("pipeline-operator/pkg/apis/algo/v1alpha1.PipelineSpec"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"pipeline-operator/pkg/apis/algo/v1alpha1.PipelineSpec"},
	}
}

func schema_pkg_apis_algo_v1alpha1_PipelineDeploymentStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "PipelineDeploymentStatus defines the observed state of PipelineDeployment",
				Properties: map[string]spec.Schema{
					"deploymentOwnerUserName": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"deploymentName": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"algoDeploymentStatuses": {
						SchemaProps: spec.SchemaProps{
							Type: []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Ref: ref("pipeline-operator/pkg/apis/algo/v1alpha1.AlgoDeploymentStatus"),
									},
								},
							},
						},
					},
					"algoPodStatuses": {
						SchemaProps: spec.SchemaProps{
							Type: []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Ref: ref("pipeline-operator/pkg/apis/algo/v1alpha1.AlgoPodStatus"),
									},
								},
							},
						},
					},
				},
			},
		},
		Dependencies: []string{
			"pipeline-operator/pkg/apis/algo/v1alpha1.AlgoDeploymentStatus", "pipeline-operator/pkg/apis/algo/v1alpha1.AlgoPodStatus"},
	}
}
