/*
 * Algo.Run API 1.0
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0
 * Contact: support@algohub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type EndpointLogData struct {

	EndpointOwnerUserName string `json:"endpointOwnerUserName,omitempty"`

	EndpointName string `json:"endpointName,omitempty"`

	MessageTimestamp time.Time `json:"messageTimestamp,omitempty"`

	StatusChanged bool `json:"statusChanged,omitempty"`

	Status string `json:"status,omitempty"`

	RunCount int32 `json:"runCount,omitempty"`

	AlgoErrorCount int32 `json:"algoErrorCount,omitempty"`

	ServerErrorCount int32 `json:"serverErrorCount,omitempty"`

	RunnerErrorCount int32 `json:"runnerErrorCount,omitempty"`

	OrchestratorErrorCount int32 `json:"orchestratorErrorCount,omitempty"`
}
