/*
 * Algo.Run API 1.0
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0
 * Contact: support@algohub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type LogMessage struct {

	Key string `json:"key,omitempty"`

	LogMessageType string `json:"logMessageType,omitempty"`

	LogTimestamp time.Time `json:"logTimestamp,omitempty"`

	Status string `json:"status,omitempty"`

	RunnerLogData *RunnerLogData `json:"runnerLogData,omitempty"`

	ServerLogData *ServerLogData `json:"serverLogData,omitempty"`

	AlgoLogData *AlgoLogData `json:"algoLogData,omitempty"`

	OrchestratorLogData *OrchestratorLogData `json:"orchestratorLogData,omitempty"`

	EndpointLogData *EndpointLogData `json:"endpointLogData,omitempty"`

	DeploymentLogData *DeploymentLogData `json:"deploymentLogData,omitempty"`

	InstanceLogData *InstanceLogData `json:"instanceLogData,omitempty"`

	HasErrors bool `json:"hasErrors,omitempty"`
}
