/*
 * Algo.Run API 1.0
 *
 * API for the Algo.Run Engine
 *
 * API version: 1.0
 * Contact: support@algohub.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type OrchestratorCommand struct {

	Command string `json:"command,omitempty"`

	EndpointDeployCmd *EndpointDeployCmd `json:"endpointDeployCmd,omitempty"`

	EndpointStopCmd *EndpointStopCmd `json:"endpointStopCmd,omitempty"`
}
